src/document/json/primitive.ts, test/yorkie_test.ts
Support Long type for yorkie-js-sdk
I tested by running `npm run test`. But I'm not sure this approach is right.🤔
After referring these two references ([r1](https://github.com/yorkie-team/yorkie/blob/master/pkg/document/json/primitive.go#L42-L66), [r2](https://github.com/yorkie-team/yorkie/blob/master/pkg/document/json/primitive.go#L42-L66)) as @hackerwins mentioned to me, I tried to figure out how can I solve it. I found out [long](https://www.npmjs.com/package/long) is used in yorki-js-sdk, so I use the library's supported method and utility. I'm not sure I did it correctly, so please feel free to feedback about my code :)
Address #1
=> Support Long type for yorkie SDK

src/document/json/primitive.ts, test/yorkie_test.ts
Support double type for yorkie-js-sdk
npm run test
I refer to this [answer](https://stackoverflow.com/questions/40970739/how-to-convert-two-16bit-integer-high-word-low-word-into-32bit-float/40970862#40970862) to deal with double type.🤔
Address #1
=> Support double type for yorkie-js-sdk

src/document/json/primitive.ts, test/yorkie_test.ts
Remove integer check condition and TODO comment
npm run test
According to the https://github.com/yorkie-team/yorkie-js-sdk/issues/1#issuecomment-633314783, I remove integer check in the getPrimitiveType function
Fixes #1
=> Remove integer check condition and TODO comment

src/document/json/primitive.ts, test/document/document_test.ts
Properties change when deleting an instance of Primitive.
It seems that it cannot be considered as immutable.
So deepcopy should not return a instance with the same memory address.
https://github.com/yorkie-team/yorkie/issues/66
=> Fix deepcopy of Primitive

dist/index.html, src/core/client.ts
Prevent bursting sync requests when the network is unavailable
1. Quit the frontend server with a keyboard interrupt (Ctrl + C)
2. Modifying contents in the CodeMirror example
Address #48
=> Prevent bursting sync requests when the network is unavailable

src/core/client.ts, src/document/document.ts, test/yorkie_test.ts
Test code for #48 
`npm test`
In both of these tests I check three things:
1. Check if remote changes can be synced automatically under normal conditions (this is already tested, but is included in order to be self-contained)
2. Simulate network error by making XHR intentionally fail. Then make sure that sync errors.
3. Let XHR be processed normally again and check that documents sync seamlessly.
There are two tests which test basically the same thing, but using different modes. One tests the above three points by manually syncing the clients, while the other uses realtime syncing and makes the test event driven.
=> Add test code for handling network error

karma.conf.js, package.json, test/yorkie_test.ts
Support testRPCAddr parameter for test code
`npm run test`
`npm run test:local`
`npm run test -- --testRPCAddr=http://localhost:8080`
ref: https://stackoverflow.com/questions/38876237/karma-start-passing-parameters
Fixes #
=> Add testRPCAddr parameter

src/util/error.ts
Change error codes from `const` object to string enums.
=> Cleanup error code with string enum

dist/drawing.html, dist/index.html, dist/quill.html, dist/util.js
Take out the `statusHolder` variable from `dist/util.js`
While refactoring code out from `dist/index.html` to `dist/util.js`, I've forgot to refactor the variable `statusHolder` as well. It worked somehow and slipped through my eyes, so I'm opening this PR to fix that.
=> Fix a function in util.js

.circleci/config.yml, package-lock.json, package.json
- Replace codecov with orbs
- We can reduce npm dependencies by using orbs provided by CircleCI
Fixes #
=> Replace codecov with orbs

test/util/llrb_tree_test.ts
Remove non-deterministic random from test code
Since the test contains non-deterministic random, the test coverage
changes each time the test is executed in CI. There are times when it
is marked with an X, in order to avoid this situation, non-deterministic
random should be removed.
#107
=> Remove non-deterministic random from test code

.gitignore, package-lock.json, package.json, src/yorkie.ts
Running `npm run build:docs` will create reference documentation in docs
folder. Distribution of the reference documentation is not included in
this commit.
```
npm install
npm run build:docs
open docs/index.html
```
- I referenced Firebase's [TypeDoc script](https://github.com/firebase/firebase-js-sdk/blob/3cf784218ddd9923ddfdde8df4c52e6b12fc5643/scripts/docgen/generate-docs.js).
- [TypeDoc options](https://github.com/TypeStrong/typedoc/blob/master/src/lib/utils/options/sources/typedoc.ts)
Fixes #98
=> Introduce TypeDoc to generate reference documentation for JS SDK

src/core/client.ts, src/document/json/object.ts, src/document/json/rht.ts, src/document/json/rich_text.ts, src/document/json/root.ts, test/document/document_test.ts, test/document/json/rht_test.ts
When splitting nodes in RichText, the logic to copy the original attributes to the new node is missing.
I also fixed some ESLint warnings that occurred.
- JS SDK: https://github.com/yorkie-team/yorkie-js-sdk/pull/136/files#diff-26660d373ad8f77f4021da7988d9aa7a1a276c75e44115439d2dd7bb91171c58R52
- Yorkie: https://github.com/yorkie-team/yorkie/blob/main/pkg/document/json/rich_text.go#L83
Fixes #135
=> Fix a bug that attributes were lost when splitting RichText nodes

src/document/json/plain_text.ts, src/document/json/rga_tree_split.ts, src/document/json/rich_text.ts, src/document/operation/edit_operation.ts, src/document/operation/rich_edit_operation.ts, src/document/proxy/rich_text_proxy.ts, src/document/proxy/text_proxy.ts, src/util/llrb_tree.ts
Moves back parameters that can be undefined.
First, I modified the function that is being used by passing `undefined` directly when calling the function.
Fixes #143
=> Moves back parameters that can be undefined

src/document/json/object.ts, src/document/proxy/object_proxy.ts, test/document/document_test.ts
Handle `Object.keys`, `Object.values` and `Object.entries`
Before this PR, `Object.keys`, `Object.values` and `Object.entries` ​​did not work properly.
```typescript
const doc = Document.create('test-col', 'test-doc');
assert.equal('{}', doc.toSortedJSON());
root.content = { a: 1, b: 2, c: 3 };
}, 'set a, b, c');
assert.equal('{"content":{"a":1,"b":2,"c":3}}', doc.toSortedJSON());
const content = doc.getRootObject().content;
assert.equal('a,b,c', Object.keys(content).join(','));
assert.equal('1,2,3', Object.values(content).join(','));
assert.equal('a,1,b,2,c,3', Object.entries(content).join(','));
```
Fixes #
=> Handle Object.keys, Object.values and Object.entries

src/core/client.ts, src/document/document.ts, src/document/proxy/proxy.ts, src/yorkie.ts, test/document/document_test.ts
Add [type parameter](https://www.typescriptlang.org/docs/handbook/generics.html) to `Document`.
When users edit a document, they can specify a type parameter to use the document more precisely.
```typescript
type Todos = { todos: Array<{ title: string; done: boolean }> };
const doc = Document.create<Todos>('test-col', 'test-doc');
root.todos = [
{ title: 'buy milk', done: false },
];
});
assert.equal(root.todos[0], {title: 'buy milk', done: false});
assert.equal(root.todos[0], {title: 'buy milk'}); // Compile Error ❌: Property 'done' is missing in type ...
```
If the type parameter is not specified, type checking is not performed as before.
```typescript
const doc = Document.create('test-col', 'test-doc');
root.anything = 'anything';
});
``` …
=> Add type parameter to Document

.eslintrc.js
Yorkie decided to use `undefined` instead of `null`, so it would be nice to use `ban-types` to avoid using null types.(#142)
We can also use ban-types to define rules like this:
```ts
function foo(): Array<T> {...}
//  vs
function foo(): []<T> {...}
```
Fixes #
=> Add ban-types for null

src/util/splay_tree.ts, test/util/splay_tree_test.ts
Fix invalid states of SplayTree when [deleting a node](https://www.codesdope.com/course/data-structures-splay-trees/#:~:text=To%20delete%20a%20node%20in,child%20of%20the%20left%20subtree.).
Address https://github.com/yorkie-team/yorkie-codepair/issues/44#issuecomment-792292239
=> Fix invalid states of SplayTree when deleting a node

examples/drawing.html, examples/index.html, examples/quill.html, src/document/document.ts, test/api/converter_test.ts, test/document/document_test.ts, test/yorkie_test.ts
Exchange the names of getRootObject and getRoot.
Users edit the document by taking the `root` variable as an argument in the
`document.update`. So it is natural to use `getRoot` to return the root.
```typescript
document.update((root) => {
root.content = 'content';
});
// AS-IS
document.getRootObject().content; // 'content'
// TO-BE
document.getRoot().content; // 'content'
```
Fixes #
=> Exchange the names of getRootObject and getRoot

src/document/change/context.ts, src/document/json/root.ts, src/document/operation/add_operation.ts, src/document/operation/edit_operation.ts, src/document/operation/remove_operation.ts, src/document/operation/rich_edit_operation.ts, src/document/operation/set_operation.ts, src/document/proxy/array_proxy.ts, src/document/proxy/object_proxy.ts, test/document/json/root_test.ts
Clean up element caches in root.ts.
In order to provide element's path to events, we need to know the parents of
elements. Therefore, when caching, we save pair and simplifies the cache for GC.
Code cleanup before addressing #155
Fixes #
=> Clean up element caches in root.ts

src/document/json/rga_tree_split.ts, test/document/document_test.ts, test/helper/helper.ts
Remove errors that occur when `insPrev` does not exist.
InsPrev can be removed due to GC, so remove the panic code added as an assertion.
Fixes https://github.com/yorkie-team/yorkie-codepair/issues/71
=> Remove errors that occur when insPrev does not exist

src/document/json/primitive.ts, test/yorkie_test.ts
For the sake of simplicity, we do not completely reproduce JavaScript's behavior, but instead, convert `undefined` to `null`.
There are `undefined` and `null` in JavaScript, but only `null` in Yorkie Document.
And there is a slight difference in the behavior of `undefined` and `null` in JavaScript. When serializing to JSON, `null` is preserved, but `undefined` disappears. In Array, `undefined` is changed to `null` and in Object, `undefined` disappears.
```typescript
> JSON.stringify({a: undefined, b: null});
< "{"b":null}"
> JSON.stringify([undefined, null])
< "[null,null]"
```
Fixes #156
=> Convert undefined to null

examples/index.html, examples/quill.html, src/core/client.ts, src/document/document.ts
Rename `Document.getKey().toIDString()` to `Document.getKey()`.
The user will use the document's Key more as a string.
```typescript
const doc = yorkie.createDocument('documents', 'doc1');
client.subscribe((event) => {
if (event.type === 'peers-changed') {
// AS-IS
// const peers = event.value[doc.getKey().toIDString()];
// TO-BE
const peers = event.value[doc.getKey()];
console.log(peers);
}
});
```
Fixes #
=> Rename `Document.getKey().toIDString()` to `Document.getKey()`

package-lock.json, package.json, tsconfig.json
Only display exported objects in JS SDK Reference
I referenced this comment https://github.com/yorkie-team/yorkie-js-sdk/pull/176#pullrequestreview-628972660
1. I upgrade the typedoc version to use [typedoc option](https://typedoc.org/guides/options/#exclude)
2. After I upgrade the typedoc version, `--ignoreCompilerErrors` was deprecated. when I generate docs, I got Lib compile error. So I added [skipLibCheck](https://www.typescriptlang.org/tsconfig#skipLibCheck) typescript config
The second step for generating document using [api-extractor](https://api-extractor.com/) will be done in this pr #176
Fixes #
=> Only display exported objects in JS SDK Reference with typedoc

src/document/json/rga_tree_list.ts, test/integration/array_test.ts
Fix the concurrent editing issue of Move Operation
https://github.com/yorkie-team/yorkie-js-sdk/issues/195
Currently, In the `findNextBeforeExecutedAt` function, we find next node with `createdAt`. I think we also need to find the next node with `movedAt`. So I add one condition
```
(node!.getNext()!.getValue().getMovedAt() &&
node!.getNext()!.getValue().getMovedAt()!.after(executedAt)))
```
I'm not sure this approach is good. So please feel free to comment on my PR :)
Fixes #195
=> Fix the concurrent editing issue of Move Operation

src/document/proxy/array_proxy.ts, test/integration/array_test.ts
Fix a bug when pushing an array element in Array
I tried deep coy of the array before `insertAfter`
```
const clone = array.deepcopy(); 
target.insertAfter(prevCreatedAt, clone);
context.registerElement(clone, target);
```
Fixes #193
=> Fix a bug when pushing an array element in Array

src/document/json/rga_tree_list.ts, src/document/proxy/array_proxy.ts, test/integration/array_test.ts, test/unit/document/document_test.ts
Implement  Array.moveLast
when we test the below code, we got an error `can't find the node` in `findNextBeforeExecutedAt` function.
```
d1.update((root) => {
const item = root['k1'].getElementByIndex(1);
root['k1'].moveAfter(item.getID());
assert.equal('{"k1":[0,2,1]}', root.toJSON());
});
```
Because the last node and the node which will move to last are the same and the node is released(deleted), the target node was not found in `findNextBeforeExecutedAt`. So I added a condition to prevent execution of insertAfter if prevNode and node are the same
I'm curious if there is another good way.
Fixes
=> Implement Array.moveLast

src/document/json/array.ts, src/document/json/rga_tree_list.ts, test/integration/array_test.ts
Modify to return `undefiend` when searching through already deleted element ID. (current version -> occur an error)
Why?
Users can try to retrieve the element with the deleted element's createdID that is already removed by garbage collection
Currently, only reflected `getElementByID`(this PR), but I wonder if `deleteByID` needs to be reflected as well
Fixes #208
=> Change function not to occur error when retrieving deleted element after garbage collection

src/api/converter.ts, src/document/json/element.ts, src/document/json/object.ts, src/document/json/rga_tree_list.ts, src/document/json/rht_pq_map.ts, src/document/proxy/object_proxy.ts, test/unit/document/document_test.ts
Remove previously inserted elements in heap when running GC.
Fixes #214
=> Remove previously inserted elements in heap when running GC

docker/docker-compose-ci.yml, src/core/client.ts, src/document/document.ts, src/yorkie.ts, test/unit/document/json/root_test.ts, webpack.config.js
export enum ClientStatus, StreamConnectionStatus, DocumentSyncResultType, ClientEventType, DocEventType
export enum ClientStatus, StreamConnectionStatus, DocumentSyncResultType, ClientEventType, DocEventType and update comments
I removed these modules because it doesn't seem to need to export 🤔 
```
export { JSONElement } from './document/json/element';
export { JSONObject } from './document/json/object';
export { JSONArray } from './document/json/array';
export { PlainText } from './document/json/plain_text';
export { RichText } from './document/json/rich_text';
```
And There was an issue not exporting other modules except for default. And I figured it out it happened because of webpack config. ` libraryExport: 'default'` https://webpack.js.org/configuration/output/#outputlibraryexport-1 …
=> Export enum and resolve issue not exporting other modules excepts for default

api-extractor.json, src/core/client.ts, src/document/document.ts
Clean up bunch of warning messages after run `npm run build`
According to this document(https://api-extractor.com/pages/setup/configure_api_report/), I redirected warnings to the API report file in the hidden folder with "reportFolder" config. In my view, some warning messages we can ignore. for example, `ae-forgotten-export`, `ae-internal-missing-underscore`. these are already set in the `api-extractor-default.json`. So I followed this rule
So after configuring `api-extractor.json`, we are getting the following messages.
- ae-missing-release-tag -> I added `@public` tag to solve it
+ to fix the following error, I added `skipLibCheck` config
```
"compiler": {
"skipLibCheck": true <--
},
```
reference: https://github.com/microsoft/rushstack/blob/master/apps/api-extractor/src/schemas/api-ext …
=> Clean up bunch of warning messages after run `npm run build`

src/document/json/rga_tree_list.ts, test/integration/array_test.ts
- fixed the array size reducing problem when deleting the same index.
- Add test
I think I don't need to do a splay operation again for the removed node, so I fixed to perform a splay operation only when deleting an undeleted node. Please let me know if it's wrong.
Fixes #225
=> Fix reduce array size when deleting the same position

docker/envoy-ci.yaml, docker/envoy.Dockerfile, docker/envoy.yaml
- Bump envoy version to 1.19.0
- Update envoy configuration
When run envoy, the following warnings are displayed:
```
[warning][main] [source/server/server.cc:610] there is no configured limit to the number of allowed active connections. Set a limit via the runtime key overload.global_downstream_max_connections
```
This warning can be resolved by adding the following configuration (taken from [here](https://github.com/envoyproxy/envoy/blob/21df5e8676a0f705709f0b3ed90fc2dbbd63cfc5/docs/root/configuration/best_practices/_include/edge.yaml#L100)):
```yaml
layered_runtime:
layers:
- name: static_layer_0
static_layer:
envoy:
resource_limits:
listener:
example_listener_name:
connection_limit: 10000
overload:
global_downstream_max_connections: 50000
```
but, if we add the above settings, …
=> Bump envoy version to 1.19.0

package-lock.json, package.json, tsconfig.json
- Let JS SDK APIs be documented.
**TL;DR**
I added two things:
- [typescript-transform-paths](https://github.com/LeDDGroup/typescript-transform-paths)
- [ts-patch](https://github.com/nonara/ts-patch)
**Why did this happen**
It was a TypeScript compiler(`tsc`)'s problem. 
We configured path aliases on #223 but TypeScript does not resolve path aliases when compile(including generating type definitions).
Hence, the import path in the type definition file(under `lib/`) was an unresolved. So, `api-extractor` referred to the source code, not the type definition file. And that's why document was not generated.
For exmaple:
```ts
/// lib/yorkie.d.ts
// expected
export { JSONArray } from "./document/json/array";
export { PlainText } from "./document/json/plain_text";
export { RichText } from …
```
=> Fix reference document

src/document/json/root.ts, test/unit/document/document_test.ts
Handle special characters in keys of the path in change events
We pass the path so the user knows which element of the document has changed. And sometimes the special characters `.` and `$` can be included in the key. To user deal with the path without confusion, I escaped the special character `$` and `.` for keys.
ex) o$j, n.um => o\$j, n\.um
In terms of the `changing path test`, in my view, it seems too big so I split to `object`, `array`, `counter`, `text`, `rich_text` test. 
Fixes #183
=> Handle special characters in keys of the path in change events

config/api-extractor.json, config/webpack.config.js, config/webpack.dev.config.js, tsconfig.json
Move `tsconfig` path from config directory to root directory
We are having alias path is not recognized warning message in vscode although we configured alias path in tsconfig and webpack. 
I found out this answer from stackoverflow. https://stackoverflow.com/questions/68625074/can-i-set-a-typescript-configuration-tsconfig-json-path-on-the-vscode-ide-to-u. it seems this error invoked because tsconfig path is not root directory. 
https://www.typescriptlang.org/docs/handbook/tsconfig-json.html
> The presence of a tsconfig.json file in a directory indicates that the directory is the root of a TypeScript project. The tsconfig.json file specifies the root files and the compiler options required to compile the project.
So I move the file to the root directory and changed base URL and etc. I'm …
=> Fix `tsconfig` is not recognized in VSCode

scripts/prune-dts.ts, src/document/document.ts, src/document/proxy/array_proxy.ts, src/document/proxy/counter_proxy.ts, src/document/proxy/object_proxy.ts, src/document/proxy/rich_text_proxy.ts, src/document/proxy/text_proxy.ts, src/yorkie.ts, test/integration/array_test.ts, test/integration/client_test.ts, test/integration/counter_test.ts, test/integration/document_test.ts, test/integration/gc_test.ts, test/integration/integration_helper.ts, test/integration/object_test.ts, test/integration/primitive_test.ts, test/integration/rich_text_test.ts, test/integration/snapshot_test.ts, test/integration/text_test.ts, test/stress/document_stress_test.ts, test/unit/api/converter_test.ts, test/unit/document/document_test.ts
The interfaces below are provided. ((Please ask for a good name suggestion.)
```
TObject
TArray
TCounter
TText
TRichText
```
When a user uses a document, the type is defined in advance.
```ts
type Doc = {
k1: string
}
const doc = DocumentReplica.create<Doc>('test', 'doc');
root['k1'] = 'hello'
})
```
If user wants to use the method provided by the proxy, can use it as follows.
```ts
type Doc = {
k1: TArray<string>
}
const doc = DocumentReplica.create<Doc>('test', 'doc');
root['k1'] = [];
const item = root['k1'].getElementByIndex(2);
})
```
If  user uses `strict: true` in tsconfig.json
must use `!` to assert. like this
```
const item = root['k1'].getElementByIndex!(2);
```
The reason for providing the optional type is when the Doc type is as …
=> Expose proxy api

.github/workflows/ci.yml, package-lock.json, src/api/converter.ts, src/core/client.ts, test/integration/client_test.ts
Fix bug when setting non-string values in Presence
Fixes #301
=> Fix bug when setting non-string values in Presence

src/document/crdt/rga_tree_split.ts, src/util/splay_tree.ts
There were some bugs in text deletion after applying range deletion.
1. Deletion is intermittently not applied in remote peers.
2. In typing in Korean, intermediate traces remain.
3. Index error when editing end of document
4. Randomly occurring runtime errors
Most of the bugs were solved by fixing the code added in #312 and #316.
Bug 4 was caused by collision with GC, so the GC was modified a little.
Fixes #
=> Fix bugs in text deletion

src/document/crdt/rga_tree_split.ts, test/integration/text_test.ts
Fix a bug when deleting blocks concurrently
When splitting a removed node, the value came alive because the
tombstone was missing in the new node.
This commit passes the tombstone when splitting.
Fixes #
=> Fix a bug when deleting blocks concurrently

src/document/json/array.ts, test/unit/document/document_test.ts
- Handle exception for array `splice()` method when the provided index is negative
- Implement array methods with objects - `includes()`, `indexOf()`, `lastIndexOf()`
```js
it('indexOf() with objects', () => {
type TestDoc = {
objects: JSONArray<{ id: string }>;
};
const doc = Document.create<TestDoc>('test-doc');
const third = { id: 'third' };
root.objects = [{ id: 'first' }, { id: 'second' }, third];
});
// test will fail 
assert.strictEqual(doc.getRoot().objects.indexOf(third), 2);
});
```
Fixes #319
=> Implement array methods with objects 

src/document/json/counter.ts, test/unit/document/document_test.ts
After creating the counter object
An issue where the constructor is executed every time the counter object is called and the value is initialized to 0.
```
call construct value =  155              counter.ts:25
call construct value =  0                  (index):136 
call1 counter object value =  155    counter.ts:25 
call construct value =  0                  (index):137 
call2 counter object value =  155    counter.ts:25 
call construct value =  0                  (index):138 
call3 counter object value =  155
```
Fixes #325
=> set value to counter initialize

examples/index.html, src/document/crdt/rga_tree_split.ts, src/document/crdt/text.ts, src/document/json/text.ts, src/util/splay_tree.ts, test/integration/text_test.ts, test/unit/util/splay_tree_test.ts
Nodes newly created then concurrently removed in the range to be deleted
had incorrect `weight` since they were not included in either `nodesToKeep`
or `nodesToDelete`. This problem causes incorrect indexing, and this commit
fixes that missing weight updates.
Fixes #331
=> Fix incorrect index for nodes newly created then concurrently removed

src/document/document.ts, test/integration/snapshot_test.ts
When a client receives a remote snapshot, the concurrent local changes
were apllied twice.
`client.syncInternal` first sends local changes to server, and then
receives remote `ChangePack`. So the snapshot in given `ChangePack`
is of the time when the local changes were already applied.
By deleting `change.execute` in `applySnapshot`, fix above problem.
Fixes #
=> Fix the problem local changes were applied twice

docker/docker-compose.yml, examples/index.html
When a client receives a snapshot, doc.root is replaced by the snapshot.
It is not detected by the remote change obsever, causing problems with
synchronization.
By adding snapshot event observer to document, value of the editor is
synced and the onChange handler re-setted for the replaced new root.
Fixes https://github.com/yorkie-team/yorkie-js-sdk/issues/347
=> Add snapshot event observer to codemirror example

.editorconfig, .prettierrc.js
Set same indent style in various editors and IDEs.
> EditorConfig helps maintain consistent coding styles for multiple developers working on the same project across various editors and IDEs. 
A plugin is required for the EditorConfig file to work. Some editors and IDEs have plugins built in. If not, you need to install plugins. To check if it's built-in, see [here](https://editorconfig.org/#download).
Fixes #341
=> Add editorconfig file to set editor default style

examples/quill.html
There was no process of deleting cursor when a peer was disconnected,
and it caused a bug in which cursors of disconnected users remained.
This commit adds the process of deleting cursors by checking for
defectors when peers are updated.
Fixes #
=> fix bug where detached remote cursors remained

src/api/converter.ts, test/integration/snapshot_test.ts
There was a bug where attributes was lost and a new line(\n) was
added when a rich text document applied snapshot from the server.
This commit fixes the bug by correcting missing process in converter.
Fixes #
=> Fix mismatch of applying snapshot of rich text

config/webpack.config.js
Compatible with non-web-like environments(e.g. server side rendering -- node)
We are using UMD as a build target format.
If the build target is UMD, Webpack uses the default value of the global object's name as `self`.
Change Webpack setting `output.globalObject` to `this` can solve this problem.
ref: [webpack configuration document](https://webpack.js.org/configuration/output/#outputglobalobject)
Fixes #373
=> fix: change global object name of webpack build output

src/document/crdt/rht.ts
Remove unused nodeMapByCreatedAt in RHT
In `RHT`, `nodeMapByCreatedAt` is required for remote deletion. However, `RHT` for representing attributes in `RichText`, doesn't currently need delete method, so this commit removes `nodeMapByCreatedAt`.
CC) @skhugh
Fixes #
=> Remove unused nodeMapByCreatedAt in RHT

src/document/time/ticket.ts, test/integration/primitive_test.ts, test/unit/document/json/primitive_test.ts
Change `lamport` from uint64 to int64
Since `lamport` is inserted directly into the DB, you need to change it from uint64 to int64.
https://github.com/yorkie-team/yorkie/pull/379
Fixes #
=> Change lamport from uint64 to int64

src/document/crdt/array.ts, src/document/crdt/element.ts, src/document/crdt/object.ts, src/document/crdt/rga_tree_list.ts, src/document/crdt/rht_pq_map.ts, src/document/crdt/root.ts, src/document/document.ts
Rename `keyOf` to `subPathOf`
`keyOf` means a sub-path of JSONPath. But it does not reveal its usage properly. So, this commit changes the name to something a little more meaningful.
Related to https://github.com/yorkie-team/yorkie-android-sdk/pull/9#issue-1382588534
=> Rename `keyOf` to `subPathOf`

examples/react-todomvc/src/App.css, examples/react-todomvc/src/Footer.tsx
Modified anchor `<a>` component with button `<button>` and added some CSS values to fit previous appearance.
~~Add `e.preventDefault()` in ` example/react-todomvc`'s `<a>` tag.~~
~~This is hard-coded solution, I recommend using button tag instead of anchor tag.~~
`<a href="/#" ...>` is causing unexpected behavior in iframe's conditions.
In https://yorkie.dev/examples/todomvc example, when you click filtering options (All, Active, Completed), you will be redirected to iframe's parent url, which is https://yorkie.dev/#.
Also, using <a> tag for button that is not performing redirection is not recommended in sematic web. I recommend using button tag instead of anchor tag.
None
=> Fix example/react-todomvc's unexpected routing in iframe conditions

src/api/converter.ts, src/document/crdt/counter.ts, src/document/crdt/primitive.ts, src/document/json/counter.ts, src/document/json/element.ts, src/document/json/object.ts, test/integration/counter_test.ts, test/unit/api/converter_test.ts, test/unit/document/document_test.ts, test/unit/document/json/counter_test.ts, test/unit/document/json/primitive_test.ts
To prevent dynamic type change of Counter, explicit type specification is required in Counter constructor. Moreover, double type is removed in Counter to mitigate confusion.
Fixes #
=> Fix the value type of Counter and remove double type from Counter

src/document/json/object.ts, test/unit/document/json/root_test.ts
Since `createText`, `createRichText`, and `createCounter` is not used and their roles are duplicated with `ObjectProxy.setInternal`, they should be removed.
Fixes #
=> Remove redundant create functions in ObjectProxy

src/api/converter.ts, src/api/yorkie/v1/resources.proto, src/api/yorkie/v1/resources_pb.d.ts, src/api/yorkie/v1/resources_pb.js, src/document/crdt/text.ts
Since TextNode.attributes have keys, this commit removes key from TextNodeAttr.
https://github.com/yorkie-team/yorkie/issues/435#issuecomment-1379859871
Fixes #
=> Remove duplicated key from TextNodeAttr

src/document/crdt/text.ts, test/integration/gc_test.ts, test/integration/text_test.ts, test/unit/document/document_test.ts
Attributes that are not present should not be included in the output.
It can be too lengthy for users who only use plain text.
```js
// as-is 
{ "contents": [{"attrs": {}, "val": "hello"}, {"attrs": {}, "val": "world"}] }
// to-be
{ "contents": ["val": "hello"}, {"val": "world"}] }`
```
Address https://github.com/yorkie-team/yorkie/issues/435#issuecomment-1371732400
=> Omit attributes if they don't exist when outputting `toJSON`

.github/workflows/npm-publish.yml, .gitignore, package.json, package.publish.json
It remove engines field in package.json when client sdk is bundled.
Bundle files that are installed as pure clients do not require nodejs engine version.
This prevents nodejs version conflicts with other libraries.
Before publishing to npm, package.json is newly configured for publish only.
Fixes #432
=> remove engines field in package.json when client sdk is bundled

src/core/client.ts, test/integration/client_test.ts
`Client.attach` can be terminated before getting peer presence map in `WatchDocuments` stream initialization. It can cause presence missing, which breaks eventual consistency, when `updatePresence` is called before the initialization.
This PR made `Client.attach` wait until the initialization is finished. Presence updates will be executed after peer presence map is properly set.
If `delay()` is removed in the code below, test in the last line intermittently fails.
https://github.com/yorkie-team/yorkie-js-sdk/blob/717383d89f119d3d2b91c2d461b38ca0b97ad1dd/test/integration/client_test.ts#L291-L309
It means the eventual values of `c1.getPeers()` and `c2.getPeers()` become different. To be precise, `c1`'s presence in `c2.getPeers()` is not updated. Although these two clients are attached to …
=> Let `Client.attach` wait until stream initialization is finished

public/counter.html, src/document/json/counter.ts, test/integration/counter_test.ts
=> Increase CRDT Counter in local change

public/counter.html, src/yorkie.ts
In this PR, I exported the type for the counter first.
Later, we can apply the default type if necessary.
- as-is
```js
// yorkie-js-sdk
export enum CounterType {
IntegerCnt,
LongCnt,
}
// counter example
root.counter = new yorkie.Counter(0, 0); // IntegerCnt(0), initial value
```
- to-be 
```js
// counter example
import yorkie from 'yorkie-js-sdk';
root.counter = new yorkie.Counter(yorkie.IntType, 0);
```
Is it better to change the order of the arguments for the default type?
```js
// as-is
root.counter = new yorkie.Counter(yorkie.LongType, 0);
// to-be
root.counter = new yorkie.Counter(0, yorkie.LongType);
root.counter = new yorkie.Counter(0); // Default is `long`
```
Fixes #439
=> Export counter type

src/document/document.ts, src/document/json/object.ts, test/integration/object_test.ts
Add the `toJS` method to the ObjectProxy's handler.
Previously, `toJSON` returns a JSON string. 
It requires an extra step of `JSON.parse` to use JSON object.
After this PR, it is easier to use the JSON object with `toJS` method.
```js
doc.subscribe((event) => {
// as-is
const rootObject = JSON.parse(doc.getRoot().toJSON());
// to-be
const rootObject = doc.getRoot().toJS();
});
```
Fixes #444
=> Add the `toJS` method to the ObjectProxy's handler

src/document/json/text.ts, test/integration/text_test.ts
Until now, user called `edit(from, to, '')` to delete content in `Text`; since it is not intuitive, `delete` and `empty` are added to `Text` data type.
```ts
root.content.delete(from, to) // delete range
root.content.empty() // delete all 
```
Fixes #450
=> Add `delete` and `empty` method to `Text` data type

config/webpack.config.js, config/webpack.dev.config.js, src/api/converter.ts
Reduce bundle size for production 
Change the webpack build configuration to reduce the bundle size.
Modify all 3 settings.
1. Separate the source-map to the outside.
2. Build in production mode and minify it.
3. Delete unnecessary packages by removing NodePolyFillPlugin. Buffer used inside is replaced with inline code.
old version bundle
new version bundle
| target | old bundle size | new bundle size(minified) | reduce |
|---|---|---|---|
| stat size | 2.11MB | `1.02MB` | -51% | 
| parsed size | 4.36MB | `544.35KB` | -87% | 
| gzipped size | 800.65KB | `95.35KB` | -88% | 
Fixes #434
=> reduce bundle size for production

src/util/splay_tree.ts, test/unit/util/splay_tree_test.ts
> Fix invalid index of SplayTree with a single node.
>
> This PR addresses an issue with the indexOf in SplayTree, which was failing to calculate the correct index when there was only one node in the tree. The conditional statement has been updated to account for this scenario.
Address https://github.com/yorkie-team/yorkie/pull/470
=> Fix invalid indexOf SplayTree with single node

test/integration/client_test.ts, test/integration/document_test.ts, test/integration/gc_test.ts, test/integration/integration_helper.ts
Add toDocKey to convert to a valid key in tests.
As the key validation logic was added to the server, the test failed, so `toDocKey` is added to change them to valid keys in tests.
Related to https://github.com/yorkie-team/yorkie/pull/467
=> Add toDocKey to convert to a valid key in tests

config/webpack.dev.config.js, config/webpack.karma.config.js
Modify the webpack config to run the `webpack-bundle-analyzer` plugin 
when using `profile:bundle` script.
It's inconvenient that the `webpack-bundle-analyzer` plugin runs every time 
we execute `npm run dev` or `npm run test`.
Fixes #
=> Modify config to run the webpack-bundle-analyzer when using `profile:bundle` script

public/counter.html, public/index.html, public/quill.html, src/core/client.ts, src/document/document.ts, test/helper/helper.ts, test/integration/client_test.ts
Clarify the ClientEvent that is sent to client.subscribe
- as-is
```ts
// js-sdk
type PeersChangedValue<P> = Record<string, Record<string, P>>;
```
- to-be
```ts
// js-sdk
type PeersChangedValue<P> = {
type: 'initialization' | 'watched' | 'unwatched' | 'presence-changed';
peers: Record<DocumentKey, Array<{ clientID: ActorID; presence: P }>>;
};
// example
client.subscribe((event) => {
switch (event.type) {
case 'status-changed': {
// event.value: activated, deactivated
break;
}
case 'stream-connection-status-changed': {
// event.value: connected, disconnected
break;
}
case 'document-synced': {
// event.value: synced, sync-failed
break;
}
case 'document-changed': {
// event.value: docKey[]
break;
}
case 'peers-changed': {
const { type, peers } = event.value;
// type: initialization, …
```
=> Clarify the ClientEvent that is sent to `client.subscribe`

src/core/client.ts, test/helper/helper.ts, test/integration/client_test.ts
After issue #464, we have additional specification changes for the peers-changed event as follows.
- Rename `initialization` to `initialized`.
- ~Change the value of the peers-changed event to the `DocPeersRecord` type.~
- ~Add the `getPeersListByDocKey` method that returns the peers array of the document.~
Address https://github.com/yorkie-team/yorkie-js-sdk/pull/464
=> Apply the updated specification for peers-changed event

src/client/attachment.ts, src/client/client.ts, test/integration/client_test.ts
Since the peer's watched/unwatched events may be missed, 
it is possible to access the presence of a non-existent peer. 
To address this, it has been modified to return undefined 
when accessing the presence of a non-existent peer.
Fixes #
=> Fix when searching for presence of non-existent peer

src/document/crdt/counter.ts, src/util/counter.ts, src/util/number.ts, test/bench/document_test.ts
Add util function for `Counter` and replace `Math.floor` method with it.
As you can see in the removed TODO below, `increase` method of `Counter` in js-sdk works different from same method in `Go` sdk.
I found out why this difference happened, and it's because `Go` removes decimal point during type casting (float to int)
Also, `long.js`, which used in js-sdk for purpose of handling large number, removes decimal point too. 
Therefore, I replace Math.floor method with this util function so that we can get the same results as others. 
(I couldn't find out detail specification on how `increase` method works, so this PR might be wrong..)
(If this PR is accepted, I'll add some description about how it works when using decimal point as a parameter) …
=> Add util function for Counter and replace Math.floor method with it

public/editor.html, public/style.css, src/api/yorkie/v1/yorkie.proto, src/api/yorkie/v1/yorkie_pb.d.ts, src/api/yorkie/v1/yorkie_pb.js, src/client/attachment.ts, src/client/client.ts, src/document/document.ts, src/yorkie.ts, test/integration/client_test.ts
- Implement Client Sync mode
- In pushOnly mode,
- Set pushOnly flag in the PushPull API.
- Don't apply remote changes.
Related https://github.com/yorkie-team/yorkie/pull/500, https://github.com/yorkie-team/yorkie-ios-sdk/pull/65
=> Add Client sync mode

src/client/client.ts, src/document/document.ts
Remove unnecessary checkpoint validation from applyChangePack.
Since we trust the server's response, we can apply the checkpoint 
received from it without further verification.
Fixes #
=> Remove unnecessary checkpoint validation from applyChangePack

public/quill.html
reported by @chacha912  (https://github.com/yorkie-team/yorkie-js-sdk/issues/491)
The cause of this issue is that `JSON.stringify` method is invoked twice. 
- <img width="820" alt="image" src="https://user-images.githubusercontent.com/46807540/233472725-3ca534c1-e468-4b25-a4a1-a0e7301521b9.png">
- https://github.com/yorkie-team/yorkie-js-sdk/blob/5a0d2b45ad9dfbaa56a197e5d083e0bb97a0b6be/src/document/crdt/text.ts#L472
- <img width="858" alt="image" src="https://user-images.githubusercontent.com/46807540/233472770-71ade315-3149-4007-a468-67c9763b51f2.png">
- https://github.com/yorkie-team/yorkie-js-sdk/blob/5a0d2b45ad9dfbaa56a197e5d083e0bb97a0b6be/public/quill.html#L173
Object `{image: "data:..."}` is over-stringified (`'"{"image": "data:...."}"'`)
Therefore, I removed the previously called …
=> Fix quill example page image rendering issue

src/document/crdt/index_tree.ts, test/unit/document/crdt/index_tree_test.ts
implements `pathToTreePos` method (find corresponding treePos from given path).
path is an array of number. Except for the last element of path, each number of path is on one-one-one response to tree node. last element of path corresponds to position
([a1, a2, a3, ..., an-1, an] where ai is an integer greater than or equal to zero)
When I checked the code of the edit method, I didn't implement `treePosToPath` because I didn't think it would be necessary to convert from treePos to path(`onChanges` directly can use given path), but if you need it, please leave a comment!
Fixes #
=> implement pathToTreePos

src/document/crdt/index_tree.ts, test/unit/document/crdt/index_tree_test.ts
implements `treePosToPath` method (find corresponding path from given treePos).
1. if treePos is `inline` or there's no parent node for `treePos.node` (which meanstreePos pointing root), push offset to `path`
2. from `treePos.node` follow linked list back to its parent node and push index of node into path
3. return reversed path 
Fixes #
=> implement treePosToPath method

src/document/document.ts, src/util/observable.ts
After RemoteChange occurs, the Subscribe event can be executed synchronously so that the application can process data synchronously and finally.
*  support Observable.nextSync() 
Fixes #502
=> support Observable.nextSync() for synchronously processing

examples/react-todomvc/src/App.tsx, examples/vanilla-codemirror6/src/main.ts, examples/vanilla-quill/src/main.ts, public/editor.html, public/index.html, public/multi.html, public/quill.html, src/document/crdt/text.ts, src/document/document.ts, src/document/json/text.ts, src/document/operation/operation.ts, src/util/observable.ts, src/yorkie.ts, test/helper/helper.ts, test/integration/client_test.ts, test/integration/text_test.ts
Remove text.onChanges and unify the event system with doc.subscribe. 
* remove Text.onChanges, onChangeHandler
* Integration with doc.subscribe
```js
const doc = Document.create<{
text: Text;
}>('test-doc');
doc.subscribe('$.text', (event) => {
if (event.type === 'remote-change') {
const changes = event.value;
for (const change of changes) {
const { operations } = change;
if (operations[0].type === 'select') {
assert.equal(operations[0].from, 2);
assert.equal(operations[0].to, 4);
}
}
}
});
root.text = new Text();
root.text.edit(0, 0, 'ABCD');
});
```
Fixes #357, Fixes #376
#502
=> Replace Text.onChanges with Document.subscribe

src/document/crdt/tree.ts, test/integration/tree_test.ts, test/unit/document/crdt/tree_test.ts
Correct `ElementNode` insert point when calling tree.edit()
Fixes #
=> Correct ElementNode insert point when edit

public/index.html, src/document/document.ts, src/util/observable.ts
Replace all of the eventStreamObserver.next() functions with synchronous forms.
* Prevents incorrect data updates when eventers run asynchronously.
* Clarify when async events are fired when using them.
Fixes #525
=> change to next method as synchronously

src/document/crdt/tree.ts, src/util/index_tree.ts, test/unit/document/crdt/tree_test.ts, test/unit/util/index_tree_test.ts
- Implement pathToPosRange which returns range of CRDTTreePos for given path
- Add TC
Fixes #
=> Implement pathToPosRange

public/prosemirror.html, src/api/converter.ts, src/document/crdt/tree.ts, src/document/json/tree.ts, src/yorkie.ts, test/unit/document/crdt/tree_test.ts
Allows selection information from the `yorkie.Tree` to be sent remotely.
support remote selection viewer.
Tree selection information is provided by the createRange () function.
```
const selection = root.tree.createRange(fromIndex, toIndex);
```
The selection is converted to a string for transmission to the remote. 
```
root.tree.createRange(from, to).map((it) => {
return yorkie.converter.toHexString(
yorkie.converter.objectToBytes(
yorkie.Primitive.of(it.offset, it.createdAt),
),
);
});
```
As you can see in the code, there is no way to simply send pos, so we wrap it in Primitive.of. 
The reason for this is so that we can transform it into bytes and send it. 
The converted selection information is then sent via root.selection to root.tree in the same way as root.tree.
```
root.selection …
```
=> Implement to make tree selection info

src/document/crdt/text.ts, src/yorkie.ts
- The comments of TextChange have been corrected.
- The textChange is not exposed to the user anymore. (`text.onchanges` has been replaced with `document.subscribe` #519 ) 
Fixes #
=> Cleanup TextChange

public/multi.html, src/document/change/change.ts, src/document/document.ts, src/document/operation/add_operation.ts, src/document/operation/edit_operation.ts, src/document/operation/increase_operation.ts, src/document/operation/move_operation.ts, src/document/operation/operation.ts, src/document/operation/remove_operation.ts, src/document/operation/select_operation.ts, src/document/operation/set_operation.ts, src/document/operation/style_operation.ts, src/document/operation/tree_edit_operation.ts, src/document/operation/tree_style_operation.ts
The `InternalOpInfo` is unnecessary since we can get the path from the root.
This was referenced from the https://github.com/yorkie-team/yorkie-ios-sdk/pull/78
Fixes #
=> Remove InternalOpInfo

CONTRIBUTING.md, README.md
This pull request addresses Issue #588 by moving the "Building & Testing" guide from README.md to CONTRIBUTING.md. The primary objective is to enhance the project's contribution guidelines and improve the developer experience for potential contributors.
- The "Building & Testing" guide content has been relocated from README.md to CONTRIBUTING.md.
- The CONTRIBUTING.md file now includes comprehensive instructions on how to build, test, and contribute effectively to the project.
- Fixes  #588
=> Move "Building & Testing" Guide to CONTRIBUTING.md

examples/vuejs-kanban/src/App.vue
restrict the condition when the kanban board(card) is opened. 
In previous version, there was only two cases , `open` is 0 or not(including null or any other positive integer value). 
So, the codes that correspoding `open` is positive integer value executed also when `open` is null because there's no difference  logically. 
It has to be one more condition to be checked that indicate open is null. 
- `open` value indicates the index of which kanban card is opend now(focused). 
- When close button is clicked, the `open` variable becomes `null` value. 
Fixes #580
=> Define more specific condition to check whether the input is opened

examples/vuejs-kanban/src/App.vue
When hot reloading occurs multiple times, the 'client.attach' request becomes pending.
So, it needs to deactivate the client when the component is unmounted.
Nope
Fixes https://github.com/yorkie-team/yorkie-js-sdk/issues/594
=> Add client deactivation before unmount

public/quill.html, src/client/client.ts, src/document/document.ts, test/helper/helper.ts, test/integration/client_test.ts, test/integration/document_test.ts, test/integration/presence_test.ts
This is a follow-up task of #574  
- Add presence to `unwatched` event
- We can use it in examples: #581 
- Return presence to user by retrieving only online clients and making a copy
When detaching, there are two possible scenarios:
When UserA detaches, a change is made to remove the presence, and the watch stream is canceled.
1) If UserB receives the `unwatched` event first, UserB will remove UserA from onlineClients and trigger the `unwatched` event.
2) If UserB receives the `pushpull` response first, which includes a change to remove presence, UserB will trigger the `unwatched` event beforehand while detaching since it involves unwatching.
Fixes #
=> Clean up methods related to presence

test/helper/helper.ts, test/integration/client_test.ts, test/integration/document_test.ts, test/integration/presence_test.ts, test/unit/document/document_test.ts
This is a follow-up to the work in https://github.com/yorkie-team/yorkie-js-sdk/pull/599/commits/b2eb6d45ef35e9b7300d8ac653538eda80479566. I modified the event-related tests to ensure deterministic behavior.
There are two ways to test events:
- When the count and order of events are known:
- Use `EventCollector.waitAndVerifyNthEvent()` to wait for the nth event to occur and verify it.
- When the count and order of events are unclear, but we need to check if certain events are received:
- Use `EventCollector.waitFor()` to verify the occurrence of specific events.
Fixes #
=> Fix event-related tests to be deterministic

src/yorkie.ts
I have added types for OperationInfo that was missing from https://yorkie.dev/yorkie-js-sdk/api-reference/yorkie-js-sdk.operationinfo.html.
| as-is | to-be| 
| :--: | :--: | 
| ![image](https://github.com/yorkie-team/yorkie-js-sdk/assets/81357083/748d39bd-675b-4915-8ba4-daa75047ff5c) | ![image](https://github.com/yorkie-team/yorkie-js-sdk/assets/81357083/3ec863c2-29ae-4e2d-974d-1e44fcb5a07b) | 
Fixes #
=> Export types related to OperationInfo

public/counter.html, public/drawing.html, public/index.html, public/multi.html, public/quill.html
- Use 'presence' event instead of 'my-presence' or 'others' when displaying online clients
- Remove unnecessary code in quill example 
- Display remote cursors when client connects to document (quill, codemirror)
- Modify selection color to be set by presence(codemirror)
Fixes #
=> Refactor presence event code in examples

src/document/operation/edit_operation.ts, src/document/operation/operation.ts, src/yorkie.ts
Remove 'selectOpInfo' as it is no longer needed. (Related https://github.com/yorkie-team/yorkie-js-sdk/pull/622)
Fixes #
=> Remove SelectOpInfo

src/api/converter.ts, src/api/yorkie/v1/resources.proto, src/api/yorkie/v1/resources_pb.d.ts, src/api/yorkie/v1/resources_pb.js, src/document/crdt/rga_tree_split.ts, src/document/crdt/text.ts, src/document/json/text.ts, src/document/operation/style_operation.ts, test/integration/text_test.ts
Currently, we are unable to check for concurrent cases when applying the `Text.setStyle` operation. This pull request introduces a `map` called `latestCreatedAtMapByActor` to track the causality between the operations of the two clients and ensures that the results converge into one.
* Add `latestCreatedAtMapByActor` to `Text.setStyle` operation
* Add related testcases
This is for applying the logic of https://github.com/yorkie-team/yorkie/pull/639
Fixes https://github.com/yorkie-team/yorkie/issues/638
=> Support concurrent formatting of Text

src/document/document.ts, test/integration/gc_test.ts
Add DisableGC option to document
Recently we have implemented multi-user undo/redo feature and added
inverse operation for Text.edit. While implementing, we noticed that
the inverse operation accessed the removed node by GC. To address this
issue, we've added the disableGC option to skip GC temporarily.
Related to https://github.com/yorkie-team/yorkie-js-sdk/pull/635
=> Add DisableGC option to document

test/integration/gc_test.ts
This PR disables real-time sync in the GC test by using the `{ isRealtimeSync: false }` option. 
While the test has luckily passed under ideal conditions, occasional failures could occur due to external factors, such as network latency. 
Additionally, I've updated the equality assertion functions to align with the JS interface, which follows the pattern `assert.equal(actual, expected)`. These changes should improve code consistency and make debugging easier.
Fixes #
=> Disable realtime sync in gc test

config/webpack.dev.config.js, package-lock.json, package.json
Previously, we replaced istanbul-instrumenter-loader with
coverage-istanbul-loader to address critical vulnerabilities.
However, this change resulted in improper line positioning within the
debugger.
To resolve this issue, this commit reverts back to using
istanbul-instrumenter-loader.
Additionally, in the future, we plan to replace the Karma-based test
runner with vitest.
Fixes #657
Related to https://github.com/yorkie-team/yorkie-js-sdk/pull/630 and https://github.com/yorkie-team/yorkie-js-sdk/pull/655
=> Recover istanbul-instrumenter-loader to use debugger

vitest.config.ts
Let vitest use multi threads to reduce the time it takes.
The test took about 20% less time(~90s to ~70s) in my local environment.
Fixes #654 #665
=> feat: remove vitest single thread config

.github/workflows/npm-publish.yml
To increase supply chain security, we should publish npm package with provenance.
Provenance data gives consumers a verifiable way to link a package back to its source repository and the specific build instructions used to publish it (see [example on npmjs.com](https://www.npmjs.com/package/@jongwooo/prism-theme-github#provenance)).
See [this page](https://github.blog/2023-04-19-introducing-npm-package-provenance/) to learn more.
Fixes #664
=> Publish npm package with provenance

.github/workflows/github-page-publish.yml, examples/nextjs-scheduler/package.json
Prevent examples from being built with Jekyll. Next.js-based examples can't load css and js assets when built with Jekyll.
Relative PR: yorkie-team/yorkie-team.github.io#106
Fixes #673
=> Disable jekyll on github actions

examples/nextjs-scheduler/app/styles/globals.css
It's hard to see the Next.js example in dark mode on the homepage.
This PR change the above screen to look like the one below.
Fixes #
=> Fit Next.js example style to the yorkie homepage

src/document/document.ts, src/document/operation/set_operation.ts, test/integration/gc_test.ts, test/unit/document/document_test.ts
Fix missing collection of removed elements from the root.
A document has two structures representing the user data: clone and root. When elements are removed by `document.update`, they are collected to `removedElementMapByCreatedAt` for garbage collection.
However, we found a bug in that the collection is missing in the root. So this commit fixes it.
A. Luckily, the collection is not missing in Yorkie.
https://github.com/yorkie-team/yorkie/blob/a000a29d81d7e6557edfbe3cb5f2ce17b203c634/pkg/document/operations/set.go#L68-L72
B. Remove `Clone` from `Document`.
We've added `clone` to protect the root from unintended updates caused by document.update. However, keeping the clone and the root in sync is challenging and consumes twice as much memory. Therefore, it is better to remove the clone …
=> Fix missing collection of removed elements from the root

test/integration/gc_test.ts
Add more GC tests to reflect current server modifications
Related to https://github.com/yorkie-team/yorkie/pull/655
=> Add more GC tests to reflect current server modifications

CHANGELOG.md, package.json, package.publish.json
Update CHANGELOG.md for v0.4.8
Fixes #
=> Update CHANGELOG.md for v0.4.8

src/document/crdt/tree.ts, test/integration/tree_test.ts, test/unit/document/crdt/tree_test.ts
Implement merge feature in `Tree.Edit`
In a text-based editor, when you have a selection that spans two paragraphs, if you press the delete key, removes the second paragraph and merges its children into the first paragraph.
For example:
- Before: `<p>a|b</p><p>c|d</p>`
- After: `<p>ad</p>`
This commit implements the merge to Tree.Edit.
```
// TODO(hackerwins): Define more clearly mergeable rules between fromParent
// and toParent. For now, if fromParent and toParent are the same
// type, then we can merge them.
```
Address https://github.com/yorkie-team/yorkie/issues/662
=> Implement merge feature in `Tree.Edit`

public/prosemirror.css, public/prosemirror.html, src/document/crdt/tree.ts, src/document/json/tree.ts, src/document/operation/tree_edit_operation.ts, test/integration/tree_test.ts, test/unit/document/crdt/tree_test.ts
Refactor ProseMirror example and Tree codes
* Refactor ProseMirror example
This commit improves the ProseMirror example by removing redundant and
unused code in both HTML and CSS, resulting in cleaner and simpler.
* Eliminate Tree.Split
Since Tree.Split is invoked during content editing, this commit removes
the separate Tree.Split, streamlining the codebase.
* Enhance Tree tests and uncomment basic text split test
In preparation for adding a split parameter to Tree.Edit, this commit
simplifies the Tree.Edit interface for better representation in a line.
Address https://github.com/yorkie-team/yorkie/issues/662
=> Refactor ProseMirror example and Tree codes

src/document/crdt/primitive.ts, src/document/json/object.ts, test/integration/object_test.ts, test/unit/document/document_test.ts
When performing a Primitive deepcopy, the absence of `removedAt` led to a problem where deleted elements reappeared. This PR addresses the issue by making sure that removedAt is included in the primitive deepcopy.
Fixes #
=> Add missing `removedAt` during Primitive deepcopy

tools/create-yorkie-app/index.ts, tools/create-yorkie-app/package.json
Fixes an issue that `create-yorkie-app` reads the wrong path when overwriting the .env.
Fixes #690
=> Fix reading wrong .env path

src/document/crdt/object.ts, src/document/crdt/rht.ts, src/document/crdt/text.ts, src/document/json/strings.ts, test/integration/text_test.ts, test/unit/document/document_test.ts
In pull request #330, when implementing the escape string function, it referred to the [js-string-escape](https://github.com/joliss/js-string-escape) library. However, we missed a point mentioned in its documentation:
> Note that the returned string is not necessarily valid JSON, since JSON disallows control characters, and `\'` is illegal in JSON.
This caused an error due to the mishandling of single quotes during the escape string process. Since we don't need to handle single quotes specially, we removed that part. (Reference: [Chromium implementation](https://github.com/chromium/chromium/blob/fc0cb60674643692171a84bb94a92c8bf5781031/base/json/string_escape.cc#L33-L79)).
We also fixed a missing part in handling escape string for object keys.
Fixes #699
=> Handle escape string for strings containing quotes

examples/nextjs-scheduler/README.md, examples/react-todomvc/README.md
This PR change typo error on example's REAMD.md!
```bash
$ docker-compose up -f docker/docker-compose.yml up 
```
to
```bash
$ docker-compose -f docker/docker-compose.yml up 
```
Maybe I'm mistaken because I don't know much about docker complex, but when I run it, it runs well when there's no **up** in front of it!
Fixes #701
=> Correct typos in the installation command on README.md in the example

src/client/client.ts, test/integration/document_test.ts
Add `removeIfNotAttached` to `client.detach()` option
(Ref: Go-SDK https://github.com/yorkie-team/yorkie/pull/560) 
**Does this PR introduce a user-facing change?**: 
When the `removeIfNotAttached` option is set during detaching, the document will be removed after detaching only if there are no other clients simultaneously editing the document (i.e., no clients are currently attached). The default setting for `removeIfNotAttached` is `false`.
```ts
await client.detach(doc, { removeIfNotAttached: true });
```
Fixes #
=> Add `removeIfNotAttached` to `client.detach()` options

src/document/crdt/tree.ts, src/document/json/tree.ts, src/document/operation/tree_edit_operation.ts, src/document/time/ticket.ts, src/util/index_tree.ts, test/integration/tree_test.ts, test/unit/document/crdt/tree_test.ts
Add test to represent duplicate node IDs in Tree.Split
https://github.com/yorkie-team/yorkie-js-sdk/blob/5be4296e5924b398003bd8c27fb16f82070445ad/src/util/index_tree.ts#L352-L382
Fixes #
=> Address duplicate node IDs in Tree.Split

src/document/crdt/tree.ts, test/integration/tree_test.ts
This PR introduces support for concurrent insertion and splitting in the Tree by utilizing `leftNode.parent` as the `parent` node.
Currently, the `parentID` and `leftSiblingID` in `CRDTTreePos` represent positions in the Tree. In other words, they help derive the `parentNode` and `leftSiblingNode` in the Tree.
When splitting an element node, the split node receives a new nodeID (#707). This complicates concurrent editing, particularly when a remote operation, unaware of the node's split, refers to child nodes that were previously in the original node but are now in the split node. In such cases, the local cannot locate the target node because the original node no longer contains those child nodes.
Fortunately, the `leftNode.parent` represents the exact parent node in the current tree. …
=> Support concurrent insertion and splitting in Tree

test/integration/tree_test.ts
This PR enhances test coverage for concurrent editing in Tree CRDT.
The 8 skipped tests correspond to the TODOs within the Tree implementation.
Fixes #
=> Add concurrent editing test cases in Tree

src/document/crdt/root.ts, test/integration/gc_test.ts
- To ensure that the `getGarbageLen` function returns the correct length, I used a Set to eliminate duplicate counting
- Add test case for `getGarbageLen`
Refer to issue [yorkie/#688](https://github.com/yorkie-team/yorkie/issues/688) for details.
Fixes # https://github.com/yorkie-team/yorkie/issues/688
=> Fix `getGarbageLen` to retrun correct size

src/document/crdt/root.ts, test/integration/document_test.ts, test/integration/gc_test.ts
* Prevent the `deregisterElement` function from deregistering twice in the nested object.
* Improve time complexity of `deregisterElement` function $O(2^n)$ to $O(n)$ when $n$ is number of elements to deregistered.
Refer to issue #715 for details.
Addresses #715
=> Prevent deregisterElement from deregistering twice in nested object

src/document/crdt/tree.ts, src/util/index_tree.ts, test/integration/tree_test.ts, test/unit/util/index_tree_test.ts
This PR introduces the logic for generating correct TreeChange in concurrent edits.
The main functionalities are collecting nodes to be deleted and creating ranges by accumulating successive nodes in pre-order.
Unlike the `Text` CRDT, `Tree` has levels and an element node has tags (`Opening`/`Closing`). 
For multi-level `Tree` operations (e.g. merge), the determination of which tag is included is currently important. However, using the existing post-order traversal, it is hard to determine if two nodes are successive and if which tags of the node are included in the range. 
As a result, This PR introduces a new traversal method that visits all kinds of tag, which include `Opening`, `Closing`, and `Text`.
**Alternatives for optimization**
Optimizing by using the linked list (`prev` and …
=> Generate correct TreeChange in concurrent edits

src/api/converter.ts, test/integration/gc_test.ts
Fix invalid tree conversion
A script error occurred when creating a snapshot due to a typo in the converter during migrating to connectRPC. This commit fixes the typo.
Fixes #
=> Fix invalid tree conversion

test/integration/tree_test.ts
This PR complements concurrent editing test cases in Tree, following #710.
It adds two more skipped tests which need to be resolved later.
Fixes #
=> Complement concurrent editing test cases in Tree

public/prosemirror.html
Fix multiple versions of prosemirror-model were loaded
Related to https://github.com/ueberdosis/tiptap/issues/577
Fixes #
=> Fix multiple versions of prosemirror-model were loaded

src/yorkie.ts
Exposes the `setLogLevel` function and `LogLevel` type, allowing SDK users to modify the log level. This prevents unintended logging from the user.
Changes in `yorkie-team.github.io` documentation: https://github.com/yorkie-team/yorkie-team.github.io/pull/118
Fixes #
=> Export `LogLevel` and `setLogLevel`

src/api/yorkie/v1/yorkie.proto, src/api/yorkie/v1/yorkie_pb.d.ts, src/api/yorkie/v1/yorkie_pb.js, src/client/client.ts
This commit restores passing sharding keys to the SDK in accordance with https://github.com/yorkie-team/yorkie/pull/776.
Fixes #
=> Restore interface changes due to server DB sharding

src/document/crdt/tree.ts, src/document/document.ts, src/document/json/tree.ts, test/integration/tree_test.ts
> ~~There was an issue with incorrect index values being returned when using `posRangeToIndexRange` within `doc.subscribe`. This problem occurred because the `subscribe` callback function was executed before the `changeID` was updated, potentially causing different index calculations.
To address this issue, the event is now published after all relevant operations are completed, ensuring the correct index values are returned when using `posRangeToIndexRange` within `doc.subscribe`.~~
>
> I have reverted the previously changes as there is no dependency between the event and changeID.
The root cause of the issue was related to the use of `getLastTimeTicket` within `PosRangeToIndexRange`.(Ref: #611 ) To find nodes, the function `findNodesAndSplitText` was used, which includes a process to …
=> Fix incorrect index returned when using posRangeToIndexRange

src/api/converter.ts, src/document/change/change.ts, src/document/change/change_id.ts, src/document/crdt/rga_tree_split.ts, src/document/crdt/text.ts, src/document/crdt/tree.ts, src/document/document.ts, src/document/time/ticket.ts
When creating a document, the InitialChangeID is used as the ChangeID, ensuring that there are no cases where actorID is undefined.
Therefore, the actorID of ChangeID and TimeTicket always exists, making it non-optional.
Fixes #552
=> Change actorID to be non-optional

src/document/crdt/rht.ts, src/document/crdt/tree.ts, src/document/json/tree.ts, src/document/operation/tree_style_operation.ts, src/document/time/ticket.ts, test/integration/tree_test.ts, test/unit/document/crdt/rht_test.ts
* Added `Tree.RemoveStyle` & `RHT.remove`, which was implemented in go-sdk but not js-sdk.
Addresses #626
Related https://github.com/yorkie-team/yorkie/pull/748
=> Implement Tree.RemoveStyle

src/util/index_tree.ts, test/integration/tree_test.ts
This patch addresses an issue arising from the `tree.edit` operation in response to problem with calculating the `fromPath` when multiple `treePos` represent a single index-based coordinate, leading to inaccuracies.
In some cases, a single index-based coordinate can be represented by multiple `treePos`, causing complications in extracting the path. To resolve this, logic has been implemented in `treePosToPath` to handle cases where `children` consist only of **text type**.
Case description: In a situation where the children of `<node>` consist only of text type nodes, and the "e" text Node has already been removed, an additional operation is made to remove the text "f".
* AS-IS: When finding treePos, if leftNode was removed, {parentNode, offset from children} was searched.(return [0, 0, …
=> Fix incorrect calculation in `indexTree.treePosToPath` operation

src/document/crdt/tree.ts, test/integration/tree_test.ts
This PR aims to resolve the issue of incorrect index calculation during tree edit when editing copy nodes, due to the missing `insPrevID` information in the `deepcopy()` process. By adding this information, the problem can be fixed.
The process of creating a document from a snapshot works fine([link](https://github.com/yorkie-team/yorkie-js-sdk/blob/0bc7ce1bf18f7d99af52feaf960b753609fba38c/src/api/converter.ts#L1055-L1061)). However, the issue arises when editing copy nodes during the editing process, as the `insPrevID` information is not copied during the `deepcopy()` process. This omission leads to incorrect index calculation. To address this, relevant modifications have been implemented in the code.
Address #754
=> Fix errors when editing Tree due to missing insPrevID in CRDTTree

examples/vanilla-quill/package.json, examples/vanilla-quill/src/main.ts, examples/vanilla-quill/src/type.ts, package-lock.json, public/quill.html, public/style.css
This PR addresses the issue of the remote cursor not being accurately displayed when local edits are made in the Quill example. It ensures that the remote cursor is correctly rendered after each edit.(Ref: [y-quill](https://github.com/yjs/y-quill/commit/29d75f1a41395fc45bc3f282428daaedccc67e06))
- before
- after
https://github.com/yorkie-team/yorkie-js-sdk/assets/81357083/5aa20715-86d7-4f92-8045-8c9636503624
It also adds extra checks to update the selection when there are differences between the selection in Yorkie and Quill. For example, if you add text before another user's selected text, Quill might include the added text in the remote-selection. In such cases, it is necessary to update the Quill selection in Yorkie.
https://github.com/yorkie-team/yorkie-js-sdk/assets/81357083/dcdefd2a- …
=> Fix issue of incorrect display of remote selection in Quill example

public/quill-two-clients.css, public/quill-two-clients.html, public/style.css, public/whiteboard.html, src/client/attachment.ts, src/client/client.ts, test/integration/client_test.ts, test/integration/counter_test.ts, test/integration/document_test.ts, test/integration/gc_test.ts, test/integration/integration_helper.ts, test/integration/object_test.ts, test/integration/presence_test.ts, test/integration/tree_test.ts
The `SyncOff` mode will allow users to maintain the watch stream functionality while disabling synchronization. 
**Does this PR introduce a user-facing change?**:
```release-note
- 1️⃣ With the addition of the `RealtimeSyncOff` mode, the `SyncMode` has been simplified into four options. Usage is as follows:
// as-is
await client.pause(doc); // manual sync
await client.resume(doc); // realtime sync(pushpull)
client.pauseRemoteChanges(doc); // pushonly 
client.resumeRemoteChanges(doc); // pushpull 
// to-be
await client.changeSyncMode(doc, SyncMode.Manual);
await client.changeSyncMode(doc, SyncMode.Realtime); // Same as PushPull mode
await client.changeSyncMode(doc, SyncMode.RealtimePushOnly); 
await client.changeSyncMode(doc, SyncMode.RealtimeSyncOff); // Added RealtimeSyncOff mode 
- 2️⃣ …
```
=> Add RealtimeSyncOff and refactor interface of SyncMode

src/document/crdt/tree.ts, test/integration/tree_test.ts
This PR addresses the issue where, in a tree data structure, when range deletion operations occur and are split into multiple events by [`makeDeletionChanges`](https://github.com/yorkie-team/yorkie-js-sdk/blob/dc9146fe04fce118616b0617494b645d3c0d8cb9/src/document/crdt/tree.ts#L1388), the order of events needs to be reversed. If you don't reverse the order, you may lead to situations where adjustments to the range are necessary for subscribers of the events.
More detailed information on this scenario can be found in issue #773.
When range deletion operations result in multiple events due to the `makeDeletionChanges()` function, in order to prevent issues for subscribers handling these events, the order of events must be reversed. By reversing the order of events, there is no need to adjust …
=> Reverse TreeChanges when Deletion Operations in Tree

src/devtools/index.ts
This PR do type-check first to avoid referencing the process object to prevents type issues when using the yorkie-js-sdk in a web browser via a CDN, etc.
Fixes #768
=> Fix issue of referencing process object on browser

src/yorkie.ts
Export OpSource
Related: https://github.com/yorkie-team/dashboard/pull/142
=> Export OpSource

src/devtools/index.ts
This PR resolves an issue encountered when using devtools in the `nextjs-scheduler` example. 
To resolve this, a condition based on the window type has been added to ensure that devtools only operates in a browser environment.
Fixes #
=> Add window type condition for using devtools

public/counter.html, public/devtool/text.css, public/index.html, public/multi.html, public/quill-two-clients.html, public/quill.html, public/style.css, public/util.js, public/whiteboard.html, src/client/client.ts, src/devtools/index.ts, src/document/document.ts, src/yorkie.ts, test/integration/client_test.ts
In this PR, `Client.subscribe()` was removed, and topics `connection` and `sync` were added to `document.subscribe()`.
Fixes #788
=> Remove Client.subscribe

test/integration/tree_concurrency_test.ts
Add Tree concurrency tests
This PR continues to work on https://github.com/yorkie-team/yorkie-js-sdk/pull/750.
Fixes #
=> Add Tree concurrency tests

public/quill-two-clients.html, src/client/client.ts, src/document/document.ts, test/integration/presence_test.ts
When the stream is disconnected, online-clients' information should be cleared and no longer accessible.
https://github.com/yorkie-team/yorkie-js-sdk/assets/81357083/c44b31b3-148a-4c5a-b953-cd32b5ce051b
> Before, the `initialized` event only occurred when first attaching to the document, indicating who was using it. Now, it also occurs if the watch stream is disconnected and clients have reset.
Address #791
=> Reset online clients when stream is disconnected

src/api/converter.ts, src/api/yorkie/v1/resources.proto, src/api/yorkie/v1/resources_pb.d.ts, src/api/yorkie/v1/resources_pb.js, src/document/crdt/rga_tree_split.ts, src/document/crdt/text.ts, src/document/crdt/tree.ts, src/document/json/tree.ts, src/document/operation/tree_style_operation.ts, test/integration/tree_concurrency_test.ts
Handle concurrent editing and styling in Tree
We will use maxCreatedAtMapByActor until the introduction of
VersionVector. https://github.com/yorkie-team/yorkie/pull/800
Related https://github.com/yorkie-team/yorkie/pull/854
=> Handle concurrent editing and styling in Tree

src/document/crdt/root.ts, test/integration/gc_test.ts
There was an issue in the garbage collection process when dealing with multiple nodes in text(tree) types. When some nodes in text were collected, the corresponding text was removed from `elementHasRemovedNodesSetByCreatedAt` in the root, preventing the GC from correctly processing the remaining nodes.
This PR addresses the inconsistency in the GC process by modifying the condition under which text is removed from `elementHasRemovedNodesSetByCreatedAt`. Instead of removing text when _**some**_ nodes are garbage collected, text will now only be removed when _**all**_ nodes have been garbage collected. This change ensures that GC behaves consistently even when multiple nodes are involved.
Fixes #
=> Fix inconsistent garbage collection for multiple nodes in text and tree type

src/document/crdt/tree.ts, src/document/document.ts, src/document/operation/operation.ts, test/integration/client_test.ts, test/integration/document_test.ts, test/integration/tree_test.ts, test/unit/document/document_test.ts
- Improve `doc.subscribe()` to infer event types appropriately based on the topic
- Complete `TODO(chacha912): Remove any type after specifying the type of DocEvent`
>
- as-is: All events are inferred as the `DocEvent`.
- to-be: The event types are inferred appropriately based on the topic.
Fixes #
=> Improve `doc.subscribe()` to infer event types appropriately based on the topic

src/client/attachment.ts, test/integration/client_test.ts
When syncmode is set to pushonly and there are no local changes, sync requests should not be triggered by remote changes.
Addresses #816
=> Avoid unnecessary syncs in push-only syncmode

src/api/converter.ts, src/devtools/index.ts, src/document/change/change_id.ts, src/document/document.ts
Add ServerSeq into ChangeInfo
Fixes #
=> Add ServerSeq into ChangeInfo

src/api/converter.ts, src/document/crdt/tree.ts, src/document/json/tree.ts, src/document/operation/operation.ts, src/document/operation/tree_style_operation.ts, src/util/index_tree.ts, test/integration/tree_concurrency_test.ts, test/integration/tree_test.ts, vitest.config.ts
This commit addresses the issue where indexes of TreeChange returned
during Tree.Style are inaccurately calculated. When executing
Tree.Style, users provide a range, but the actual execution is based
on nodes. This commit corrects the calculation of the TreeChange index
by basing it on nodes, resolving the issue.
Address https://github.com/yorkie-team/yorkie/issues/882
Related https://github.com/yorkie-team/yorkie-android-sdk/pull/193
=> Fix incorrect indexes in TreeChange

src/api/converter.ts, test/bench/tree.bench.ts
Enhance tree conversion for better performance
The time complexity of creating converter.fromTreeNodes was O(N^2), potentially causing performance bottlenecks. It's optimized to O(n) with this commit.
While this may not be a significant issue currently, there is a risk that as the number of tree nodes in the protobuf increases, operations will scale quadratically, potentially causing performance bottlenecks.
Fixes yorkie-team/yorkie#930
=> Improve performance for creating crdt.TreeNode

.github/workflows/ci.yml, .github/workflows/create-yorkie-app-publish.yml, .github/workflows/devtools-publish.yml, .github/workflows/github-page-publish.yml, .github/workflows/npm-publish.yml, packages/sdk/CHANGELOG.md, packages/sdk/package.json
Update CHANGELOG.md for v0.4.31
Fixes #
=> Update CHANGELOG.md for v0.4.31

packages/sdk/.eslintrc.js, packages/sdk/package.json, packages/sdk/src/document/crdt/object.ts, packages/sdk/src/document/json/tree.ts
Scope: `packages/sdk`
- Add Linting script
- Ignore ESLint scope(test, build, bench, d.ts)
---
Follow #1016 
---
I have a question about our current test file naming conventions. Here’s a summary:
| Package           | Test Type      | Naming Pattern      |
|-------------------|----------------|---------------------|
| **packages/sdk**  | Unit           | `*_test.ts`         |
|                   | Integration    | `*_test.ts`         |
|                   | Bench          | `*.bench.ts`        |
| **packages/schema** | Unit         | `*.test.ts`         |
- The `_test` suffix in **packages/sdk** was carried over from Go’s testing conventions.
- We could unify on a single separator (either `.` or `_`) for consistency, **or**
- We could keep the current patterns to preserve the Go-inspired …
=> Cleanup ESLint packages/sdk
