- dist/drawing.html
- dist/index.html
- src/core/client.ts
- src/document/document.ts
- src/document/json/array.ts
- src/document/json/rga.ts
- src/document/proxy/array_proxy.ts
- src/document/proxy/object_proxy.ts
- src/document/proxy/proxy.ts
- src/document/proxy/text_proxy.ts
- src/yorkie.ts
- test/yorkie_test.ts
- webpack.dev.config.js
- Add drawing example
- Support native interface for the return value of `doc.getRootObject()`
- https://github.com/yorkie-team/yorkie-js-sdk/issues/9
> support drawing sample

- .circleci/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
- karma.conf.js
- package.json
- test/yorkie_test.ts
Add .circleci/config.yml
Add .github/PULL_REQUEST_TEMPLATE.md
Fixes #7
> Add .circleci/config.yml

- karma.conf.js
- package-lock.json
- package.json
- src/document/json/array.ts
- src/document/json/element.ts
- src/document/json/primitive.ts
- src/document/json/rga.ts
- src/document/operation/remove_operation.ts
- src/document/proxy/array_proxy.ts
- test/document/document_test.ts
Add Array.removeByID and Array.getElementByIndex
- https://github.com/yorkie-team/yorkie-team.github.io/pull/12
> Add Array.removeByID and Array.getElementByIndex

- src/document/json/rga.ts
- src/document/proxy/array_proxy.ts
- test/document/document_test.ts
- test/yorkie_test.ts
Add Array.insertAfter
- https://github.com/yorkie-team/yorkie-team.github.io/pull/12
> Add Array.insertAfter

- src/api/converter.ts
- src/document/json/array.ts
- src/document/json/element.ts
- src/document/json/rga_tree_list.ts
- src/document/proxy/array_proxy.ts
- test/document/document_test.ts
Replace Array's elements with RGATreeList
https://github.com/yorkie-team/yorkie/issues/1
> Replace Array's elements with RGATreeList

- src/document/proxy/object_proxy.ts
Remove duplicate codes
Fixes #23
> Remove duplicate codes

- src/document/json/primitive.ts
- test/yorkie_test.ts
Support date, byte array type for yorkie-js-sdk
npm run test
I use `Long` library's supported method and utility to deal with `Date` type.
Address #1
> Support date, byte array type for yorkie-js-sdk

- src/core/client.ts
- Fix to run watchloop again when deactivating clients or detaching documents
- #47 failed and we try to fix the bug in this PR
> Fix to run watchloop again when deactivating clients or detaching documents

- src/core/client.ts
- src/document/json/primitive.ts
- src/util/logger.ts
When using enum, enumerated numbers are assigned a value whose default
value increases from 0. So there is no need to indicate the value.
Fixes #
> Cleanup enum

- package-lock.json
- package.json
> Remove ncu

- test/yorkie_test.ts
Close #67 
`npm test`
Remove `setTimeout` from tests and make it event driven if needed.
> Remove setTimeouts from tests

- src/core/client.ts
- src/document/checkpoint/checkpoint.ts
- src/util/observable.ts
Did some miscellaneous cleanups while reading the code.
> Miscellaneous cleanup

- dist/drawing.html
- dist/index.html
- dist/quill.html
- dist/style.css
- dist/util.js
- src/core/client.ts
- test/yorkie_test.ts
> Display network status in examples

- .eslintrc.js
- README.md
- package-lock.json
- package.json
- src/core/client.ts
- src/document/change/change.ts
- src/document/document.ts
- src/document/proxy/array_proxy.ts
- src/util/heap.ts
- src/util/observable.ts
- src/util/splay_tree.ts
- test/document/document_test.ts
- test/yorkie_test.ts
Introduce Husky to do automated code styling
Fixes #53
> Introduce Husky

- .circleci/config.yml
- karma.conf.js
- package-lock.json
- package.json
- webpack.dev.config.js
> Introduce CodeCov

- CONTRIBUTING.md
- README.md
Add contribution guide based on [yorkie repository](https://github.com/yorkie-team/yorkie
)
read readme.md and contribution.md
Fixes #
> add contribution guide for readme.md

- test/document/json/rht_test.ts
Add a test file for `src/document/json/rht.ts`
Run `npm run test`
Nope
Fixes #
> Add a test file for json/rht

- src/core/client.ts
- src/util/logger.ts
In the existing log, not only string arguments but also other values can be used.
Fixes #99
> Changed to allow log all values

- src/document/json/rga_tree_split.ts
Add nodesToDelete type
Fixes #
> Assert nodesToDelete type

- CHANGELOG.md
- package.json
Preparatory work for the release of Version 0.1.1.
Fixes #
> Update to version 0.1.1

- src/document/json/rga_tree_split.ts
Fix typo findFloorNodePerferToLeft to findFloorNodePreferToLeft
Fixes #
> Fix typo findFloorNodePerferToLeft to findFloorNodePreferToLeft

- .github/workflows/npm-publish.yml
Add npm-publish action.
Add an action to be automatically distributed to npm when creating a
release.
Fixes #
> Add npm-publish action

- CHANGELOG.md
Add additional features in CHANGELOG.md for release.
Fixes #
> Add additional features in 0.1.1

- .eslintrc.js
- package-lock.json
- package.json
- src/api/converter.ts
- src/core/client.ts
- src/document/document.ts
- src/document/json/rich_text.ts
- src/document/operation/edit_operation.ts
- src/document/proxy/proxy.ts
- src/util/comparator.ts
- src/util/splay_tree.ts
- test/api/converter_test.ts
- test/document/document_test.ts
- test/document/json/rht_test.ts
- test/helper/helper.ts
- test/yorkie_test.ts
- tsconfig.json
This PR continues to #125.
Fixes #94
> Mojosoeun fix/strict mode

- .eslintrc.js
- src/api/converter.ts
- src/core/client.ts
- src/document/json/rich_text.ts
- src/yorkie.ts
If the variable name and field name are the same, do not need to specify
a separate value.
If all conditions are not met, an error is raised and null can never be
returned.
Fixes #
> Cleanup converter

- test/document/json/counter_test.ts
move counter_test's path from `test/json` to `test/document/json`
Fixes #
> move counter_test's path from `test/json` to `test/document/json`

- CHANGELOG.md
- package-lock.json
- package.json
Add additional features in CHANGELOG.md for release.
Fixes #
> Update CHANGELOG for release 0.1.2

- src/document/json/array.ts
- src/document/json/object.ts
- src/document/json/rga_tree_list.ts
- src/document/json/rht_pq_map.ts
- src/document/proxy/array_proxy.ts
- src/document/proxy/object_proxy.ts
- test/document/document_test.ts
- test/document/json/root_test.ts
Fix script error that occurred when deleting value using missing key or index.
As with the JavaScript behavior, it has been fixed so that no script error
occurs when the user deletes the missing key or index.
Fixes #
> Fix script error that occurred when deleting a value using missing key or index.

- examples/index.html
- examples/quill.html
- examples/util.js
- src/core/client.ts
- src/document/document.ts
- src/document/operation/select_operation.ts
- src/yorkie.ts
- test/helper/helper.ts
- test/yorkie_test.ts
Define the event types strictly.
Code cleanup before addressing #155
Fixes #
> Define the event types strictly

- src/api/converter.ts
- src/document/json/primitive.ts
- src/document/operation/select_operation.ts
- test/document/document_test.ts
- test/document/json/primitive_test.ts
- test/yorkie_test.ts
Support for null values.
We need to merge https://github.com/yorkie-team/yorkie/pull/160 first.
Fixes #156
> Support for null values

- test/document/json/primitive_test.ts
Add primitive tests
1. add primitive type test
2. add valueFromBytes test
If we need more tests for the primitive type, please feel free to comment on PR!
Fixes #
> Add primitive tests

- src/document/json/rga_tree_split.ts
- src/util/splay_tree.ts
- test/document/document_test.ts
- test/helper/helper.ts
- test/yorkie_test.ts
Fix text divergence that occurs between `Document` and external editor.
~Occurs after the introduction of [garbage collection in text](https://github.com/yorkie-team/yorkie-js-sdk/issues/124).~
Fixes https://github.com/yorkie-team/yorkie-codepair/issues/68
> Fix text divergence that occurs between Document and external editor.

- src/document/json/rht.ts
> Fix the typo comment

- examples/index.html
- examples/quill.html
- src/document/json/plain_text.ts
- src/document/json/rich_text.ts
- src/document/operation/select_operation.ts
- src/document/proxy/rich_text_proxy.ts
- src/document/proxy/text_proxy.ts
- test/document/document_test.ts
Rename `updateSelection` to `select` to keep it consistent with Agent.
Fixes #
> Rename updateSelection to select

- .github/workflows/github-page-publish.yml
Add a github action for publishing reference documentation using GitHub Pages.
Fixes #163
> Add a github action for publishing reference documentation using GitHub Pages

- CHANGELOG.md
- package.json
Update CHANGELOG for v0.1.3
Fixes #
> Update CHANGELOG for v0.1.3

- src/core/client.ts
- src/document/document.ts
- test/integration/client_test.ts
Define ClientEvent more strictly.
Address #181
> Define ClientEvent more strictly

- src/document/json/root.ts
- test/integration/client_test.ts
- test/unit/document/document_test.ts
Fix a bug occurs when setting an empty string as a key.
Fixes #
> Fix a bug occurs when setting an empty string as a key

- src/document/json/rga_tree_list.ts
- src/document/proxy/array_proxy.ts
- test/unit/document/document_test.ts
Fix a bug that the first element of an array was not deleted.
Fixes #
> Fix a bug that the first element of an array was not deleted

- src/document/json/rga_tree_list.ts
- src/document/proxy/array_proxy.ts
- test/unit/document/document_test.ts
Fix a bug that the size of the array increases when moving element
Fixes #
> Fix a bug that the size of the array increases when moving element

- src/document/proxy/array_proxy.ts
- test/unit/document/document_test.ts
Fix a bug that did not move after pushing in the same update.
https://github.com/yorkie-team/yorkie-js-sdk/issues/187#issuecomment-840974867
Fixes #187
> Fix a bug that did not move after pushing in same update

- CHANGELOG.md
- package.json
Update CHANGELOG for v0.1.4.
Fixes #
> Update CHANGELOG for v0.1.4

- src/document/json/array.ts
- src/document/json/rga_tree_list.ts
- src/document/operation/move_operation.ts
- src/document/proxy/array_proxy.ts
- test/integration/array_test.ts
- test/unit/document/document_test.ts
Add `moveFront` function to put an item in front of an array
Fixes #90
> Implement `moveFront` feature

- src/document/proxy/array_proxy.ts
- test/integration/array_test.ts
- test/unit/document/document_test.ts
Implement Array.moveAfter
move an element after a specific position in the array
Fixes #202
> Implement Array.moveAfter

- src/document/proxy/array_proxy.ts
- test/integration/array_test.ts
- test/unit/document/document_test.ts
Add `Array.insertBefore` function to inserts the node before the given previous node
Fixes #198
> Implement Array.insertBefore feature

- CHANGELOG.md
- package.json
Update CHANGELOG for v0.1.5
Fixes #
> Update CHANGELOG for v0.1.5

- src/document/json/array.ts
- test/integration/array_test.ts
Check removed status when searching the document array based on `Timeticket`
Fixes #
> Check removed element

- CHANGELOG.md
- package.json
Update CHANGELOG for v0.1.6
Fixes #
> Update CHANGELOG for v0.1.6

- docker/docker-compose.yml
- docker/envoy.yaml
Improve explanations about setting envoy to connect to yorkie gRPC server when using Linux machine.
This PR "[Add comments to help configure envoy and yorkie containers #131](https://github.com/yorkie-team/yorkie-codepair/pull/131)" in yorkie-team/yorkie-codepair deals with the same issue.
.
> Add explanations about setting envoy

- src/api/converter.ts
- src/core/client.ts
- src/yorkie.ts
It can be inferred metadata type
- It can be checked type when using `getMetadata`
- It can be inferred value when using `updateMetadata` 
Fixes #239
> Add generic to metadata

- api-extractor.json
- tsconfig.json
Fix not recognized relative path alias in test files
1. include 'test/**/*'
2. change mainEntry of api-extractor
Fixes #249
> Fix issue not recognized relative path alias in test files

- examples/quill.html
http://localhost:9000/quill.html page is broken. so I fixed quill example page
1. update color-hash
2. add quill-cursors
Fixes #250
> Fix quill example page

- CHANGELOG.md
- package.json
- src/document/document.ts
Update CHANGELOG for v0.1.10
Fixes #
> Update CHANGELOG for v0.1.10

- CHANGELOG.md
- package-lock.json
- package.json
Update CHANGELOG for v0.1.11
Fixes #
> Update CHANGELOG for v0.1.11

- .github/workflows/github-page-publish.yml
- .npmrc
- README.md
- package-lock.json
- package.json
To check proper node.js and npm version.
https://github.com/yorkie-team/codepair/issues/151
#261
> Check node.js and npm version. (#261)

- README.md
The link to the js-docs documentation was incorrect, so I changed the link.
> Fix docs url

- package-lock.json
- package.json
Fix vulnerability for yorkie-js-sdk
run `npm audit fix` and `npm audit fix --force` to reslove vulnerability
Fixes #
> Fix vulnerability for yorkie-js-sdk

- package-lock.json
- package.json
Upgrade istanbul-instrumenter-loader version
After i run `npm audit fix`, I found out there is moderate vulnerability issue. So i fixed it
Fixes #
> Upgrade istanbul-instrumenter-loader version

- .github/workflows/ci.yml
- package-lock.json
- package.json
Bump up libs for keeping the project up to date.
- google-protobuf: 3.14.0 -> 3.19.4
- grpc-web: 1.2.1 -> 1.3.1
- long: 4.0.0 -> 5.0.0
Fixes #
> Bump up libs

- docker/envoy-ci.yaml
- docker/envoy.yaml
- src/core/auth.ts
- src/core/client.ts
Add apiKey option
If the user creates a client with `public_key` of a project as apiKey,
the user can manage the client in the project.
https://github.com/yorkie-team/yorkie/issues/310
> Add apiKey option

- examples/drawing.html
- examples/index.html
- examples/quill.html
- src/document/json/counter.ts
- src/document/json/plain_text.ts
- src/document/json/rich_text.ts
- src/document/proxy/counter_proxy.ts
- src/document/proxy/object_proxy.ts
- src/document/proxy/proxy.ts
- src/document/proxy/rich_text_proxy.ts
- src/document/proxy/text_proxy.ts
- src/yorkie.ts
- test/helper/helper.ts
- test/integration/client_test.ts
- test/integration/counter_test.ts
- test/integration/document_test.ts
- test/integration/gc_test.ts
- test/integration/integration_helper.ts
- test/integration/rich_text_test.ts
- test/integration/text_test.ts
- test/stress/document_stress_test.ts
- test/unit/api/converter_test.ts
- test/unit/document/document_test.ts
Replace `createXXX` with `new XXX`
Address #298
> Replace `createXXX` with `new XXX`

- examples/drawing.html
- examples/index.html
- examples/quill.html
- src/document/json/counter.ts
- src/document/json/plain_text.ts
- src/document/json/rich_text.ts
- src/document/proxy/counter_proxy.ts
- src/document/proxy/object_proxy.ts
- src/document/proxy/proxy.ts
- src/document/proxy/rich_text_proxy.ts
- src/document/proxy/text_proxy.ts
- src/yorkie.ts
- test/helper/helper.ts
- test/integration/client_test.ts
- test/integration/counter_test.ts
- test/integration/document_test.ts
- test/integration/gc_test.ts
- test/integration/integration_helper.ts
- test/integration/rich_text_test.ts
- test/integration/text_test.ts
- test/stress/document_stress_test.ts
- test/unit/api/converter_test.ts
- test/unit/document/document_test.ts
> Replace with new

- .github/workflows/ci.yml
- config/karma.conf.js
- package-lock.json
- package.json
- src/document/document.ts
- test/bench/document_test.ts
- tsconfig.json
Add benchmark step for js-sdk
1. @ppeeou and I add benchmark step for js-sdk during ci step using [benchmark github action](https://github.com/benchmark-action/github-action-benchmark)
2. add just one bench mark code
Fixes #248
> Add benchmark step for js-sdk

- .github/workflows/ci.yml
Run Store benchmark result only if not forked repo
Fixes #
> Run Store benchmark result only if not forked repo

- CHANGELOG.md
- package.json
- src/document/json/strings.ts
> Update CHANGELOG for v0.2.11

- test/bench/document_test.ts
polish(refactor) the benchmark test code
- apply destructuring
- consistant Document's instance name
- delete 'as' keyword(benchmark is 'export default' class)
- change from imperative to declarative(`for(;;)` -> `string.prototype.repeat()`)
Fixes #
> Polish benchmark test code

- CHANGELOG.md
- package.json
- src/document/json/strings.ts
> Update CHANGELOG for v0.2.12

- test/bench/document_test.ts
Add benchmark Document/equals_test to JS SDK.
Fixes #
> Add benchmark document equals test

- .github/workflows/ci.yml
Fix invalid forked repository condition
Fixes #339
> Fix invalid forked repository condition

- test/bench/document_test.ts
Add benchmark Document/nested_update_test to JS SDK.
Fixes #
> Add benchmark document nested update test

- examples/quill.html
- examples/style.css
- src/document/crdt/rich_text.ts
Support quill embeds type to example project
It's a follow-up to #340.
Fixes #32
> Support quill embeds type to example project

- test/bench/document_test.ts
Add benchmark Document/delete_test to JS SDK.
Fixes #
> Add benchmark document delete test

- examples/quill.html
This commit adds snapshot event observer to Quill example
and refactor it. (same changes with #360)
I think this commit should be applied first to correct a bug with applying https://github.com/yorkie-team/yorkie-js-sdk/pull/354, 
Fixes #
> Add snapshot event observer to Quill example

- config/webpack.config.js
- package-lock.json
- package.json
- src/api/converter.ts
- src/document/document.ts
- src/yorkie.ts
> Chacha912 history

- CHANGELOG.md
- package.json
> Update CHANGELOG for v0.2.15

- CHANGELOG.md
- package.json
> Update CHANGELOG for v0.2.16

- examples/index.html
- examples/quill.html
- src/core/client.ts
- src/document/change/change.ts
- src/document/change/change_id.ts
- src/document/change/checkpoint.ts
- src/document/crdt/rga_tree_list.ts
- src/document/crdt/rga_tree_split.ts
- src/document/crdt/rich_text.ts
- src/document/crdt/text.ts
- src/document/document.ts
- src/document/json/rich_text.ts
- src/document/json/text.ts
- src/document/operation/add_operation.ts
- src/document/operation/edit_operation.ts
- src/document/operation/increase_operation.ts
- src/document/operation/move_operation.ts
- src/document/operation/operation.ts
- src/document/operation/remove_operation.ts
- src/document/operation/rich_edit_operation.ts
- src/document/operation/select_operation.ts
- src/document/operation/set_operation.ts
- src/document/operation/style_operation.ts
- src/document/time/ticket.ts
- src/util/splay_tree.ts
- test/integration/gc_test.ts
- test/integration/rich_text_test.ts
- test/integration/text_test.ts
- test/unit/document/json/root_test.ts
- test/unit/util/splay_tree_test.ts
Change some names to be the same as App SDK for consistency
Related to https://github.com/yorkie-team/yorkie-android-sdk/pull/7
> Change some names to be the same as App SDK for consistency

- src/document/crdt/rga_tree_list.ts
- src/document/crdt/rht_pq_map.ts
Fix things reported during App SDK review
This commit fixes the improvements to the JS SDK that were reported
while reviewing PR in App SDK.
Related to https://github.com/yorkie-team/yorkie-android-sdk/pull/9 https://github.com/yorkie-team/yorkie-android-sdk/pull/10
> Fix things reported during App SDK review

- examples/vanilla-codemirror6/.gitignore
- examples/vanilla-codemirror6/README.md
- examples/vanilla-codemirror6/index.html
- examples/vanilla-codemirror6/package-lock.json
- examples/vanilla-codemirror6/package.json
- examples/vanilla-codemirror6/src/main.ts
- examples/vanilla-codemirror6/src/network.ts
- examples/vanilla-codemirror6/src/style.css
- examples/vanilla-codemirror6/src/utils.ts
- examples/vanilla-codemirror6/src/vite-env.d.ts
- examples/vanilla-codemirror6/tsconfig.json
- package-lock.json
Added example of integrating Yorkie and CodeMirror6 based on TypeScript, without any framework.
Fixes #393 
----
perhaps the contents of README may be poor. feel free to let me know if you have any feedback
> Add CodeMirror6 integration example

- test/bench/document_test.ts
- test/bench/index.ts
Add benchmark Document/equals_test and Document/nested_update_test to updated benchmark scripts
Fixes #
> Add removed benchmark test

- src/document/json/array.ts
- src/util/heap.ts
- test/unit/document/document_test.ts
- test/unit/util/heap_test.ts
Fix issues identified during iOS SDK development
https://github.com/yorkie-team/yorkie-ios-sdk/pull/27
Fixes #
> Fix issues identified during iOS SDK development

- examples/vuejs-kanban/.gitignore
- examples/vuejs-kanban/README.md
- examples/vuejs-kanban/index.html
- examples/vuejs-kanban/package-lock.json
- examples/vuejs-kanban/package.json
- examples/vuejs-kanban/src/App.vue
- examples/vuejs-kanban/src/assets/main.css
- examples/vuejs-kanban/src/main.js
- examples/vuejs-kanban/vite.config.js
Add vuejs-kanban example
Manage Vue-based kanban board example in JS SDK project.
Fixes #
> Add vuejs-kanban example

- examples/react-todomvc/.gitignore
- examples/react-todomvc/index.html
- examples/react-todomvc/package-lock.json
- examples/react-todomvc/package.json
- examples/react-todomvc/src/App.css
- examples/react-todomvc/src/App.tsx
- examples/react-todomvc/src/Footer.tsx
- examples/react-todomvc/src/Header.tsx
- examples/react-todomvc/src/MainSection.tsx
- examples/react-todomvc/src/TodoItem.tsx
- examples/react-todomvc/src/TodoTextInput.tsx
- examples/react-todomvc/src/main.tsx
- examples/react-todomvc/src/model.ts
- examples/react-todomvc/src/vite-env.d.ts
- examples/react-todomvc/tsconfig.json
- examples/react-todomvc/tsconfig.node.json
- examples/react-todomvc/vite.config.ts
Add react-todomvc example
Fixes #
> Add react-todomvc example

- src/document/crdt/primitive.ts
Use UNIX timestamp for date value.
https://github.com/yorkie-team/yorkie/blob/main/pkg/document/crdt/primitive.go#L176
Related to https://github.com/yorkie-team/yorkie/pull/432
> Use UNIX timestamp for date value

- test/bench/document_test.ts
> Parkeunae add benchmark document object test

- examples/profile-stack/main.js
- examples/profile-stack/style.css
A client that accesses the document to show the Event log has been added. 
This client does not have presence information, so I add exception handling.
Fixes #
> Handle for when there is no information in presence on profile-stack example

- src/document/crdt/rga_tree_split.ts
- src/document/crdt/text.ts
- src/document/json/text.ts
- src/yorkie.ts
- test/helper/helper.ts
Remove JSON(Text) Dependency from RGATreeSplit in CRDT 
Fixes #
> Remove Text Dependency from RGATreeSplit

- public/counter.html
- public/style.css
Add counter example to test Counter type 
Fixes #
> Add counter example to test Counter type 

- CHANGELOG.md
- package.json
- package.publish.json
Update version: v0.3.0
Fixes #
> Update version: v0.3.0

- MAINTAINING.md
- examples/profile-stack/main.js
- examples/profile-stack/package-lock.json
- examples/profile-stack/package.json
- examples/react-tldraw/package-lock.json
- examples/react-tldraw/package.json
- examples/react-todomvc/package-lock.json
- examples/react-todomvc/package.json
- examples/vanilla-codemirror6/package-lock.json
- examples/vanilla-codemirror6/package.json
- examples/vanilla-quill/.env.production
- examples/vanilla-quill/package-lock.json
- examples/vanilla-quill/package.json
- examples/vanilla-quill/src/main.ts
- examples/vanilla-quill/src/utils.ts
- examples/vuejs-kanban/package-lock.json
- examples/vuejs-kanban/package.json
- package-lock.json
- public/quill.html
- public/style.css
- public/util.js
Update version to v0.3.0 in examples & Update MAINTAINING.md
Fixes #
> Update version to v0.3.0 in examples

- CHANGELOG.md
- package.json
- package.publish.json
Update package.json and CHANGELOG.md
Fixes #
> Update package.json and CHANGELOG.md

- examples/profile-stack/package-lock.json
- examples/profile-stack/package.json
- examples/react-tldraw/package-lock.json
- examples/react-tldraw/package.json
- examples/react-todomvc/package-lock.json
- examples/react-todomvc/package.json
- examples/vanilla-codemirror6/package-lock.json
- examples/vanilla-codemirror6/package.json
- examples/vanilla-codemirror6/src/main.ts
- examples/vanilla-quill/package-lock.json
- examples/vanilla-quill/package.json
- examples/vanilla-quill/src/main.ts
- examples/vuejs-kanban/package-lock.json
- examples/vuejs-kanban/package.json
- package-lock.json
1. Update version to v0.3.2 in examples.
2. Update  `TextChange`'s `change` to `change.value!` in `vanilla-codemirror6` and `vanilla-quill` examples.
Fixes #
> Update version to v0.3.2 in examples

- config/webpack.config.js
In production mode, yorkie-js-sdk.js do not must minified.
yorkie-js-sdk.js is not must minified.
yorkie-js.sdk.min.js is automatically created in cdnjs.
#473
> add optimization option in production mode

- .eslintrc.js
- examples/vanilla-quill/src/main.ts
- src/yorkie.ts
- test/integration/gc_test.ts
- test/unit/api/converter_test.ts
- test/unit/document/json/root_test.ts
Add naming convention rule for variables
A naming convention rule is added for the consistency of variable names.
Fixes #
> Add naming convention rule for variables

- src/core/client.ts
- test/integration/client_test.ts
Add pause and resume to Client
Fixes #
> Add pause and resume to Client

- CHANGELOG.md
- package.json
- package.publish.json
Update CHANGELOG.md for releasing new version
Fixes #
> Update CHANGELOG.md for releasing new version

- examples/profile-stack/main.js
- examples/profile-stack/package.json
- examples/react-tldraw/package.json
- examples/react-tldraw/src/hooks/useMultiplayerState.ts
- examples/react-todomvc/package.json
- examples/vanilla-codemirror6/package.json
- examples/vanilla-codemirror6/src/main.ts
- examples/vanilla-codemirror6/src/utils.ts
- examples/vanilla-quill/package.json
- examples/vanilla-quill/src/main.ts
- examples/vanilla-quill/src/utils.ts
- examples/vuejs-kanban/package.json
- package-lock.json
- public/quill.html
Update version to v0.3.3 in examples
Fixes #
> Update version to v0.3.3 in examples

- docker/envoy-ci.yaml
- docker/envoy.yaml
- src/client/client.ts
Add x-shard-key to APIs
Fixes #
> Add x-shard-key to APIs

- src/document/crdt/array.ts
- src/document/json/array.ts
- test/bench/document_test.ts
add benchmark tests for Document 
(the contents listed below are things that cannot be done)
- array type tests (array type is not implemented as same as in yorkie(Go), so I can't find the way to finish this.. plz give me some advice if its possible) 
- text delete test for size 100,000 (calls stack size exceeded)
- Add couple todos to check
Fixes https://github.com/yorkie-team/yorkie-js-sdk/issues/306
> Add benchmark tests

- CHANGELOG.md
- package.json
- package.publish.json
Update CHANGELOG for v0.3.4
Fixes #
> Update CHANGELOG for v0.3.4

- examples/profile-stack/package.json
- examples/react-tldraw/package.json
- examples/react-todomvc/package.json
- examples/vanilla-codemirror6/package.json
- examples/vanilla-quill/package.json
- examples/vuejs-kanban/package.json
- package-lock.json
Update version to v0.3.4 in examples
Fixes #
> Update version to v0.3.4 in examples

- CHANGELOG.md
- package.json
- package.publish.json
Update CHANGELOG for v0.3.5.
Fixes #
> Update CHANGELOG for v0.3.5

- examples/profile-stack/package.json
- examples/react-tldraw/package.json
- examples/react-todomvc/package.json
- examples/vanilla-codemirror6/package.json
- examples/vanilla-quill/package.json
- examples/vuejs-kanban/package.json
- package-lock.json
Update version to v0.3.5 in examples.
Fixes #
> Update version to v0.3.5 in examples

- CHANGELOG.md
- package.json
- package.publish.json
Update CHANGELOG for v0.4.1
Fixes #
> Update CHANGELOG for v0.4.1

- examples/profile-stack/package.json
- examples/react-tldraw/package.json
- examples/react-todomvc/package.json
- examples/vanilla-codemirror6/package.json
- examples/vanilla-codemirror6/src/main.ts
- examples/vanilla-quill/package.json
- examples/vanilla-quill/src/main.ts
- examples/vuejs-kanban/package.json
- package-lock.json
Update version to v0.4.1 in examples.
Fixes #
> Update version to v0.4.1 in examples

- src/document/crdt/tree.ts
- src/document/json/tree.ts
Implement `createRangeByPath` for selection.
Fixes #
> Implement createRangeByPath for selection

- CHANGELOG.md
- package.json
- package.publish.json
Update CHANGELOG for v0.4.2.
Fixes #
> Update CHANGELOG for v0.4.2

- examples/profile-stack/package.json
- examples/react-tldraw/package.json
- examples/react-todomvc/package.json
- examples/vanilla-codemirror6/package.json
- examples/vanilla-quill/package.json
- examples/vuejs-kanban/package.json
- package-lock.json
Update version to v0.4.2 in examples.
Fixes #
> Update version to v0.4.2 in examples

- src/document/change/context.ts
- src/document/crdt/element.ts
- src/document/crdt/rga_tree_split.ts
- src/document/crdt/root.ts
- src/document/crdt/text.ts
- src/document/crdt/tree.ts
- src/document/json/text.ts
- src/document/json/tree.ts
- src/document/operation/edit_operation.ts
- src/document/operation/tree_edit_operation.ts
- test/integration/gc_test.ts
- Apply garbage collection to tree
-  change`CRDTTextElement` to `CRDTGarbageCollectionElement` and let CRDTTree to extend it 
Fixes #
> Apply garbage collection to tree

- src/document/crdt/tree.ts
- src/util/index_tree.ts
- test/integration/gc_test.ts
- make it traverse whole tree (includes tombstones) when collecting garbage
- `node.children` returns alived nodes only, thus removed nodes were not deleted.
Fixes #
> Fix garbage collection bug

- CHANGELOG.md
- package.json
- package.publish.json
> update change log to release v0.4.3

- package.json
- package.publish.json
- src/document/json/tree.ts
- src/document/operation/operation.ts
- src/yorkie.ts
Update CHANGELOG.md for v0.4.4
Fixes #
> Update CHANGELOG.md for v0.4.4

- src/document/json/tree.ts
- expose `pathToIndex` api
- to let users to set selection by using path 
Fixes #
> Expose pathToIndex API

- CHANGELOG.md
- package.json
- package.publish.json
Update CHANGELOG.md for v0.4.5
Fixes #
> Update CHANGELOG.md for v0.4.5

- package-lock.json
- package.json
Fix build errors on Node.js 18+
This error fixed on [webpack@5.61.0](https://github.com/webpack/webpack/releases/tag/v5.61.0) by implementing md4
Fixes #582
> fix: build error on node 18+

- examples/react-tldraw/README.md
fix typo of react-tldraw example's README.md
Fixes #
> fix: react-tldraw readme typo

- src/document/operation/operation.ts
Add comments for OperationInfo
Fixes #
> Add comments for OperationInfo

- src/api/yorkie/v1/resources.proto
- src/api/yorkie/v1/resources_pb.d.ts
- src/api/yorkie/v1/resources_pb.js
- src/api/yorkie/v1/yorkie.proto
- src/api/yorkie/v1/yorkie_pb.d.ts
- src/api/yorkie/v1/yorkie_pb.js
- src/client/client.ts
- Remove unnecessary client information from the protobuf response
- Change `clientID` type from `bytes` to `string` in the API 
Related https://github.com/yorkie-team/yorkie/issues/498
> Cleanup proto

- src/document/crdt/tree.ts
Fix invalid path of style changes
Related to #611
> Fix invalid path of style changes

- src/document/crdt/tree.ts
- src/util/index_tree.ts
- test/integration/tree_test.ts
- test/unit/document/crdt/tree_test.ts
- test/unit/util/index_tree_test.ts
This is for applying the logic in https://github.com/yorkie-team/yorkie/pull/624#issue-1860840589
> Support multi-level and parital element selection

- CHANGELOG.md
- package.json
- package.publish.json
Update CHANGELOG.md for v0.4.6
Fixes #
> Update CHANGELOG.md for v0.4.6

- src/api/converter.ts
Recover Select to prevent unsupported operation
Related to https://github.com/yorkie-team/yorkie-js-sdk/pull/622
> Recover Select to prevent unsupported operation

- src/document/crdt/tree.ts
- src/util/index_tree.ts
- test/bench/document_test.ts
Add Tree.Edit benchmark and improve performance and fix a bit of code to improve performance
Thanks to @hackerwins, he helps to me find out performance degradation point related to https://github.com/yorkie-team/yorkie/issues/635 this issue. 
Fixes #
> Add Tree.Edit benchmark and improve performance

- CHANGELOG.md
- package.json
- package.publish.json
Update CHANGELOG.md for v0.4.7
Fixes #
> Update CHANGELOG.md for v0.4.7

- examples/nextjs-scheduler/package.json
- examples/profile-stack/package.json
- examples/react-tldraw/package.json
- examples/react-todomvc/package.json
- examples/simultaneous-cursors/package.json
- examples/vanilla-codemirror6/package.json
- examples/vanilla-quill/package.json
- examples/vuejs-kanban/package.json
- package-lock.json
Update examples version to v0.4.7
Fixes #
> Update examples version to v0.4.7

- examples/README.md
- examples/nextjs-scheduler/next.config.js
Update nextjs-scheduler to export static files to `./dist`
Fixes #
> Update nextjs-scheduler to export static files

- CHANGELOG.md
- package.json
- package.publish.json
Update CHANGELOG.md for v0.4.9
Fixes #
> Update CHANGELOG.md for v0.4.9

- CHANGELOG.md
- package.json
- package.publish.json
Update CHANGELOG.md for v0.4.11
Fixes #
> Update CHANGELOG.md for v0.4.11

- CHANGELOG.md
- package.json
- package.publish.json
Update CHANGELOG.md for v0.4.12
Fixes #
> Update CHANGELOG.md for v0.4.12

- CHANGELOG.md
- package.json
- package.publish.json
Update CHANGELOG.md for v0.4.13-rc
Fixes #
> Update CHANGELOG.md for v0.4.13-rc

- examples/nextjs-scheduler/package.json
- examples/profile-stack/package.json
- examples/react-tldraw/package.json
- examples/react-todomvc/package.json
- examples/simultaneous-cursors/package.json
- examples/vanilla-codemirror6/package.json
- examples/vanilla-quill/package.json
- examples/vuejs-kanban/package.json
- package-lock.json
Update examples version to v0.4.12
Fixes #
> Update examples version to v0.4.12

- CONTRIBUTING.md
Update protobuf description in CONTRIBUTING.md
Fixes #
> Update protobuf description in CONTRIBUTING.md

- CHANGELOG.md
- package.json
- package.publish.json
Update CHANGELOG.md for v0.4.13-rc2
Fixes #
> Update CHANGELOG.md for v0.4.13-rc2

- src/yorkie.ts
Export devtools type to use in tools/devtools
Fixes #
> Export devtools type

- CHANGELOG.md
- package.json
- package.publish.json
Update CHANGELOG.md for v0.4.13
Fixes #
> Update CHANGELOG.md for v0.4.13

- examples/nextjs-scheduler/package.json
- examples/profile-stack/package.json
- examples/react-tldraw/package.json
- examples/react-todomvc/package.json
- examples/simultaneous-cursors/package.json
- examples/vanilla-codemirror6/package.json
- examples/vanilla-quill/package.json
- examples/vuejs-kanban/package.json
Update examples version to v0.4.13
Fixes #
> Update examples version to v0.4.13

- src/document/crdt/rht.ts
- src/document/crdt/tree.ts
- test/integration/tree_test.ts
Fix invalid `TreeChange`s in concurrent `Tree.Style`
Related to https://github.com/yorkie-team/yorkie-android-sdk/pull/149
> Fix invalid `TreeChange`s in concurrent `Tree.Style`

- CHANGELOG.md
- package.json
- package.publish.json
Update CHANGELOG.md for v0.4.14-rc
Fixes #
> Update CHANGELOG.md for v0.4.14-rc

- CHANGELOG.md
- package.json
- package.publish.json
Update CHANGELOG.md for v0.4.14
Fixes #
> Update CHANGELOG.md for v0.4.14

- CHANGELOG.md
- package.json
- package.publish.json
Update CHANGELOG.md for v0.4.15-rc
Fixes #
> Update CHANGELOG.md for v0.4.15-rc

- CHANGELOG.md
- package.json
- package.publish.json
Update CHANGELOG.md for v0.4.15-rc2
Fixes #
> Update CHANGELOG.md for v0.4.15-rc2

- CHANGELOG.md
- package.json
- package.publish.json
Update CHANGELOG.md for v0.4.15
Fixes #
> Update CHANGELOG.md for v0.4.15

- CHANGELOG.md
- package.json
- package.publish.json
Update CHANGELOG.md for v0.4.16
Fixes #
> Update CHANGELOG.md for v0.4.16

- test/integration/client_test.ts
- test/integration/document_test.ts
- test/integration/presence_test.ts
- test/unit/document/document_test.ts
Remove unnecessary stubs from the test code
In #760, we are redefining DocEvent. I've left a `TODO` to update the types from `any` to more specific once DocEvent becomes more refined.
Fixes #
> Remove unnecessary stubs from the test code

- CHANGELOG.md
- package.json
- package.publish.json
Update CHANGELOG.md for v0.4.17
Fixes #
> Update CHANGELOG.md for v0.4.17

- CHANGELOG.md
- package.json
- package.publish.json
Update CHANGELOG.md for v0.4.18-rc
Fixes #
> Update CHANGELOG.md for v0.4.18-rc

- .github/workflows/ci.yml
- .github/workflows/github-page-publish.yml
- .github/workflows/npm-publish.yml
- README.md
- package-lock.json
- package.json
- tsconfig.json
- vitest.config.ts
> Cache npm and node_modules in CI

- package-lock.json
- public/counter.html
- public/drawing.html
- public/index.html
- public/multi.html
- public/prosemirror.html
- public/quill-two-clients.html
- public/quill.html
- public/whiteboard.html
- src/document/document.ts
- tools/devtools/README.md
- tools/devtools/package-lock.json
- tools/devtools/package.json
- tools/devtools/src/devtools/contexts/YorkieSource.tsx
- tools/devtools/src/devtools/panel/index.tsx
- tools/devtools/src/devtools/tabs/History.tsx
Update yorkie-js-sdk v0.4.18-rc in devtools
Related: #760
> Update yorkie-js-sdk v0.4.18-rc in devtools

- examples/nextjs-scheduler/.env.production
- examples/nextjs-scheduler/next.config.js
- examples/nextjs-scheduler/package.json
- examples/nextjs-scheduler/tsconfig.json
- examples/profile-stack/package.json
- examples/react-tldraw/package.json
- examples/react-todomvc/package.json
- examples/simultaneous-cursors/package.json
- examples/vanilla-codemirror6/package.json
- examples/vanilla-quill/package.json
- examples/vuejs-kanban/package.json
- package-lock.json
Update examples version to v0.4.18
Fixes #
> Update examples version to v0.4.18

- .github/workflows/create-yorkie-app-publish.yml
- .github/workflows/devtools-publish.yml
Update GitHub Action workflow for create-yorkie-app
Related to https://github.com/yorkie-team/yorkie-js-sdk/pull/783
Fixes #
> Update GitHub Action workflow for create-yorkie-app

- examples/profile-stack/main.js
- examples/react-tldraw/src/hooks/useMultiplayerState.ts
- examples/simultaneous-cursors/src/App.jsx
- examples/vanilla-codemirror6/src/main.ts
- examples/vanilla-quill/src/main.ts
- examples/vuejs-kanban/src/App.vue
Add `enableDevtools` flag to examples
Fixes #
> Add enableDevtools flag to examples

- examples/simultaneous-cursors/src/App.jsx
In the homepage example, a client participates for the event log. However, this client does not have the proper presence value. Therefore, an exception handling for this client has been added in `simultaneous-cursors` example.
Fixes #705
> Handle exception for the client without proper presence value in example 

- package-lock.json
- package.json
- public/counter.html
- public/drawing.html
- public/index.html
- public/multi.html
- public/prosemirror.html
- public/quill-two-clients.html
- public/quill.html
- public/whiteboard.html
- vite.config.ts
- vite.preview.ts
Add vite-plugin-dts to build yorkie-js-sdk.d.ts
Fixes #
> Add vite-plugin-dts to build yorkie-js-sdk.d.ts

- src/document/crdt/rht.ts
- src/document/crdt/tree.ts
- test/integration/tree_test.ts
Fix incorrect tree style changes
Generate `TreeChangeType.Style` events by filtering out only the affected properties.
Fixes #757
> Fix invalid tree style changes

- CHANGELOG.md
- package.json
Update CHANGELOG.md for v0.4.19
Fixes #
> Update CHANGELOG.md for v0.4.19

- examples/nextjs-scheduler/package.json
- examples/profile-stack/package.json
- examples/react-tldraw/package.json
- examples/react-todomvc/package.json
- examples/simultaneous-cursors/package.json
- examples/vanilla-codemirror6/package.json
- examples/vanilla-codemirror6/src/main.ts
- examples/vanilla-codemirror6/src/network.ts
- examples/vanilla-quill/package.json
- examples/vanilla-quill/src/main.ts
- examples/vanilla-quill/src/network.ts
- examples/vuejs-kanban/package.json
- package-lock.json
Update exmples version to v0.4.19
Fixes #
> Update exmples version to v0.4.19

- .github/workflows/cr.yml
Add ChatGPT-CodeReview
Fixes #
> Add ChatGPT-CodeReview

- CHANGELOG.md
- package.json
Update CHANGELOG.md for v0.4.21-rc
Fixes #
> Update CHANGELOG.md for v0.4.21-rc

- src/document/crdt/tree.ts
Fix invalid error message in CRDTTreePos
Fixes #
> Fix invalid error message in CRDTTreePos

- CHANGELOG.md
- package.json
Update CHANGELOG.md for v0.4.21-rc3
Fixes #
> Update CHANGELOG.md for v0.4.21-rc3

- CHANGELOG.md
- package.json
Update CHANGELOG.md for v0.4.21
Fixes #
> Update CHANGELOG.md for v0.4.21

- examples/nextjs-scheduler/package.json
- examples/profile-stack/package.json
- examples/react-tldraw/package.json
- examples/react-todomvc/package.json
- examples/simultaneous-cursors/package.json
- examples/vanilla-codemirror6/package.json
- examples/vanilla-quill/package.json
- examples/vuejs-kanban/package.json
- package-lock.json
Update examples version to v0.4.21
Fixes #
> Update examples version to v0.4.21

- CHANGELOG.md
- package.json
Update CHANGELOG.md for v0.4.23
Fixes #
> Update CHANGELOG.md for v0.4.23

- CHANGELOG.md
- package.json
Update CHANGELOG.md for v0.4.25
Fixes #
> Update CHANGELOG.md for v0.4.25

- examples/nextjs-scheduler/package.json
- examples/profile-stack/package.json
- examples/react-tldraw/package.json
- examples/react-todomvc/package.json
- examples/simultaneous-cursors/package.json
- examples/vanilla-codemirror6/package.json
- examples/vanilla-quill/package.json
- examples/vuejs-kanban/package.json
- package-lock.json
Update example version to v0.4.25
Fixes #
> Update example version to v0.4.25

- CHANGELOG.md
- package.json
Update CHANGELOG.md for v0.4.26
Fixes #
> Update CHANGELOG.md for v0.4.26

- CHANGELOG.md
- package.json
Update CHANGELOG.md for v0.4.28
Fixes #
> Update CHANGELOG.md for v0.4.28

- .github/workflows/npm-publish.yml
Update npm-publish command for sdk
Related to https://github.com/pnpm/pnpm/issues/5894
Fixes #
> Update npm-publish command for sdk

- CHANGELOG.md
- packages/sdk/package.json
Update CHANGELOG.md for v0.5.0
Fixes #
> Update CHANGELOG.md for v0.5.0

- examples/profile-stack/main.js
- examples/simultaneous-cursors/src/App.jsx
- examples/vuejs-kanban/src/App.vue
Update client initialization to use rpcAddr option in examples
Related #975
> Update client initialization to use rpcAddr option in examples

- CHANGELOG.md
- packages/react/package.json
- packages/schema/package.json
- packages/sdk/package.json
Update CHANGELOG.md for v0.6.9
Fixes #
> Update CHANGELOG.md for v0.6.9

- CHANGELOG.md
- packages/react/package.json
- packages/schema/package.json
- packages/sdk/package.json
Update CHANGELOG.md for v0.6.10
Fixes #
> Update CHANGELOG.md for v0.6.10

- CHANGELOG.md
- packages/react/package.json
- packages/schema/package.json
- packages/sdk/package.json
Update CHANGELOG.md for v0.6.24
Fixes #
> Update CHANGELOG.md for v0.6.24
